<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<metadata>
    <map>
        <entry>
            <key>DISPLAYNAME</key>
            <value>Task_Send_back_template_to_ES_for_Updating.php</value>
        </entry>
        <entry>
            <key>DATE_MODIFICATION</key>
            <value>1618373378798</value>
        </entry>
        <entry>
            <key>REPOSITORY</key>
            <value>Process</value>
        </entry>
        <entry>
            <key>DATE_CREATION</key>
            <value>1618373378791</value>
        </entry>
        <entry>
            <key>TAG</key>
        </entry>
        <entry>
            <key>FILE_TYPE</key>
            <value>text</value>
        </entry>
        <entry>
            <key>TYPE</key>
            <value>UPLOAD</value>
        </entry>
        <entry>
            <key>COMMENT</key>
        </entry>
    </map>
</metadata>
