<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<metadata>
    <map>
        <entry>
            <key>FILE_TYPE</key>
            <value>text</value>
        </entry>
        <entry>
            <key>DATE_MODIFICATION</key>
            <value>1554992104821</value>
        </entry>
        <entry>
            <key>DATE_CREATION</key>
            <value>1554297853591</value>
        </entry>
        <entry>
            <key>TYPE</key>
            <value>FILE</value>
        </entry>
    </map>
</metadata>
