<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<metadata>
    <map>
        <entry>
            <key>DISPLAYNAME</key>
            <value>Decommission_CE_Remove_CE_and_update_IPAM.py</value>
        </entry>
        <entry>
            <key>DATE_MODIFICATION</key>
            <value>1613065059594</value>
        </entry>
        <entry>
            <key>REPOSITORY</key>
            <value>Process</value>
        </entry>
        <entry>
            <key>DATE_CREATION</key>
            <value>1613065059589</value>
        </entry>
        <entry>
            <key>TAG</key>
        </entry>
        <entry>
            <key>FILE_TYPE</key>
            <value>text</value>
        </entry>
        <entry>
            <key>TYPE</key>
            <value>UPLOAD</value>
        </entry>
        <entry>
            <key>COMMENT</key>
        </entry>
    </map>
</metadata>
