<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<metadata>
    <map>
        <entry>
            <key>DISPLAYNAME</key>
            <value>Task_create_handler.py</value>
        </entry>
        <entry>
            <key>DATE_MODIFICATION</key>
            <value>1613123670525</value>
        </entry>
        <entry>
            <key>REPOSITORY</key>
            <value>OpenMSA_WF_Password_Manager</value>
        </entry>
        <entry>
            <key>DATE_CREATION</key>
            <value>1613123670520</value>
        </entry>
        <entry>
            <key>TAG</key>
        </entry>
        <entry>
            <key>FILE_TYPE</key>
            <value>text</value>
        </entry>
        <entry>
            <key>TYPE</key>
            <value>UPLOAD</value>
        </entry>
        <entry>
            <key>COMMENT</key>
        </entry>
    </map>
</metadata>
