<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-02 at 21:03:01.
 */

require_once dirname(__FILE__) . '/../Nal/api/app/all_resource.php';

class all_resourceTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var all_resource
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        if( !defined('PHPUNIT_RUN')) {
            define( 'PHPUNIT_RUN', 1 );
        }
        $this->homeDir = realpath( dirname(__FILE__) ) ;
        if( !defined('HOME_DIR')) {
            define( 'HOME_DIR', $this->homeDir );
        }
        if( !defined('API_DIR')) {
            define( 'API_DIR' , HOME_DIR . '' );
        }
        if( !defined('APP_DIR')) {
            define( 'APP_DIR' , API_DIR . '/Stub' );
        }
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers all_resource::get
     * @todo   Implement testGet().
     */
    public function testGet(){

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'all_resource';
        $_SERVER['REQUEST_URI']          = '/test/resource';

        $ret = new all_resource();
        $method = new ReflectionMethod( $ret, 'get' );
        $method->setAccessible( true );

        $countInfo = array(
            'contract_info' => array(
                '0' => array(
                    'test' => '1'
                ),
                '1' => array(
                    'test2' => '2'
                )
            ),
        );

        $execList = array(
            'pod_info' => array(
                '0' => array(
                    'pod_id'   => 'pod0001',
                    'use_type' => '1',
                ),
                '1' => array(
                    'pod_id'   => 'pod0002',
                    'use_type' => '3',
                ),
            ),
            'apl_info' => array(
                '0' => array(
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID'             => '1',
                    'node_id'        => '1234',
                ),
                '1' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '2',
                    'node_id'        => '2345',
                ),
                '2' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '2',
                    'node_id'        => '3456',
                )
            )
        );

        $openStackCnt = array(
            'vcpus' => array(
                'quota' => 10,
                'use_cnt' => 3,
                'contract_cnt' => 5,
            ),
            'disk' => array(
                'quota' => 16000,
                'use_cnt' => 1000,
                'contract_cnt' => 5000,
            ),
            'ram' => array(
                'quota' => 5000,
                'use_cnt' => 400,
                'contract_cnt' => 4000,
            ),
        );

        $wimResult = array(
            'result' => array(
                'status' => 'success'
            ),
            'data' => array(
                'wim_check_flg' => '1',
                'contract_info' => array(
                    'test' => '1'
                )
            )
        );

        // case 1
        $stb = $this->getMock('all_resource',array( '_execMultiApi', '_getOpenStackCnt', '_execApi', '_getContInfo', 'success' ));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnValue($execList));
        $stb->expects($this->any())->method('_getOpenStackCnt')->will($this->returnValue($openStackCnt));
        $stb->expects($this->any())->method('_execApi')->will($this->returnValue($wimResult));
        $stb->expects($this->any())->method('_getContInfo')->will($this->returnValue($countInfo));
        $stb->expects($this->any())->method('success')->will($this->returnArgument(0));
        $this->assertEquals( $method->invoke($stb),'');

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'all_resource';
        $_SERVER['REQUEST_URI']    = '/test/resource';

        $ret = new all_resource();
        $method = new ReflectionMethod( $ret, 'get' );
        $method->setAccessible( true );

        $execList = array(
            'pod_info' => array(
                '0' => array(
                    'pod_id'   => 'pod0001',
                    'use_type' => '1',
                ),
                '1' => array(
                    'pod_id'   => 'pod0002',
                    'use_type' => '3',
                ),
            ),
            'apl_info' => array(
                '0' => array(
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID'             => '1',
                    'node_id'        => '1234',
                ),
                '1' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '2',
                    'node_id'        => '2345',
                ),
                '2' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '2',
                    'node_id'        => '3456',
                )
            )
        );

        $countInfo = array(
            'contract_info' => array(
                '0' => array(
                    'test' => '1'
                ),
                '1' => array(
                    'test2' => '2'
                )
            ),
        );

        $wimResult = array(
            'result' => array(
                'status' => 'error',
                'error-code' => 'NAL110001',
                'message' => 'wim error'
            ),
            'data' => array(
            )
        );

        // case 2
        $stb = $this->getMock('all_resource',array( '_execMultiApi', '_getOpenStackCnt', '_execApi', '_getContInfo', 'success' ));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnValue($execList));
        $stb->expects($this->any())->method('_getOpenStackCnt')->will($this->returnValue($openStackCnt));
        $stb->expects($this->any())->method('_execApi')->will($this->returnValue($wimResult));
        $stb->expects($this->any())->method('_getContInfo')->will($this->returnValue($countInfo));
        $stb->expects($this->any())->method('success')->will($this->returnArgument(0));

        try {
            $method->invoke($stb);
        }catch( Exception $e){
            $this->assertEquals($e->getMessage(),'wim error');
        }

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'all_resource';
        $_SERVER['REQUEST_URI']          = '/test/resource';

        $ret = new all_resource();
        $method = new ReflectionMethod( $ret, 'get' );
        $method->setAccessible( true );

        $countInfo = array(
            'contract_info' => array(
                '0' => array(
                    'test' => '1'
                ),
                '1' => array(
                    'test2' => '2'
                )
            ),
        );

        $wimResult = array(
            'result' => array(
                'status' => 'success'
            ),
            'data' => array(
                'wim_check_flg' => '1',
                'test' => '1'
            )
        );

        // case 3
        $stb = $this->getMock('all_resource',array( '_getTenant', '_execMultiApi', '_execApi', '_getContInfoTenant', 'success' ));
        $stb->expects($this->any())->method('_getTenant')->will($this->returnValue('1234'));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnValue($execList));
        $stb->expects($this->any())->method('_execApi')->will($this->returnValue($wimResult));
        $stb->expects($this->any())->method('_getContInfoTenant')->will($this->returnValue($countInfo));
        $stb->expects($this->any())->method('success')->will($this->returnArgument(0));
        $stb->_p['IaaS_tenant_id'] = '1234';
        $this->assertEquals( $method->invoke($stb),'');

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'all_resource';
        $_GET['pod_id']            = 'pod0001';
        $_GET['dc_id']             = 'dc02';
        $_GET['use_type']          = '2';
        $_SERVER['REQUEST_URI']    = '/test/resource/';

        $ret = new all_resource();
        $method = new ReflectionMethod( $ret, 'get' );
        $method->setAccessible( true );

        $info = array(
            'vcpus' => array(
                'quota'   => 10,
                'use_cnt' => 2,
            ),
            'disk' => array(
                'quota'   => 16800,
                'use_cnt' => 3000,
            ),
            'ram' => array(
                'quota'   => 7000,
                'use_cnt' => 400,
            )
        );

        // case 4
        $stb = $this->getMock('all_resource',array( '_execProcess', 'success' ));
        $stb->expects($this->any())->method('_execProcess')->will($this->returnValue($info));
        $stb->expects($this->any())->method('success')->will($this->returnArgument(0));
        $stb->_nalConf['api_type'] = 'wim'; // WIM
        $this->assertEquals( $method->invoke($stb),'');

        unset( $_GET['pod_id'] );
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'all_resource';
        $_SERVER['REQUEST_URI']    = '/test/resource/';

        $ret = new all_resource();
        $method = new ReflectionMethod( $ret, 'get' );
        $method->setAccessible( true );

        $wim_info = array(
            'dc_group_info'  => array(),
            'dc_member_info' => array(),
            'wan_info'       => array(),
        );

        // case 5
        $stb = $this->getMock('all_resource',array( '_execMultiApi', 'success' ));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnValue($wim_info));
        $stb->expects($this->any())->method('success')->will($this->returnArgument(0));
        $stb->_nalConf['api_type'] = 'wim'; // WIM
        $this->assertEquals( $method->invoke($stb),'');

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'all_resource';
        $_SERVER['REQUEST_URI']          = '/test/resource/';

        $ret = new all_resource();
        $method = new ReflectionMethod( $ret, 'get' );
        $method->setAccessible( true );

        // case 6
        $stb = $this->getMock('all_resource',array( '_execMultiApi', '_execProcess', 'success' ));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnArgument(0));
        $stb->expects($this->any())->method('success')->will($this->returnArgument(0));
        $stb->_nalConf['api_type'] = 'wim'; // WIM
        $stb->_p['IaaS_tenant_id'] = '1234';
        $stb->_p['tenant_name']    = 'tenant1';
        $this->assertEquals( $method->invoke($stb),'');

        $wimResult = array(
            'result' => array(
                'status' => 'error',
                'error-code' => 'NAL110001',
                'message' => 'wim error'
            ),
            'data' => array(
            )
        );

        // case 7
        $stb = $this->getMock('all_resource',array( '_getTenant', '_execMultiApi', '_execApi', 'success' ));
        $stb->expects($this->any())->method('_getTenant')->will($this->returnValue('1234'));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnValue($execList));
        $stb->expects($this->any())->method('_execApi')->will($this->returnValue($wimResult));
        $stb->expects($this->any())->method('success')->will($this->returnArgument(0));
        $stb->_p['IaaS_tenant_id'] = '1234';

        try {
            $method->invoke($stb);
        }catch( Exception $e){
            $this->assertEquals($e->getMessage(),'wim error');
        }        $countInfo = array(
            'contract_info' => array(
                '0' => array(
                    'test' => '1'
                ),
                '1' => array(
                    'test2' => '2'
                )
            ),
        );

        $execList = array(
            'pod_info' => array(
                '0' => array(
                    'pod_id'   => 'pod0001',
                    'use_type' => '1',
                ),
            ),
            'apl_info' => array(
                '0' => array(
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID'             => '1',
                    'node_id'        => '1234',
                ),
                '1' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '2',
                    'node_id'        => '2345',
                ),
                '2' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '2',
                    'node_id'        => '3456',
                )
            )
        );

        // case 8
        $stb = $this->getMock('all_resource',array( '_execMultiApi', '_getOpenStackCnt', '_getContInfo', 'success' ));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnValue($execList));
        $stb->expects($this->any())->method('_getOpenStackCnt')->will($this->returnValue($openStackCnt));
        $stb->expects($this->any())->method('_getContInfo')->will($this->returnValue($countInfo));
        $stb->expects($this->any())->method('success')->will($this->returnArgument(0));
        $this->assertEquals( $method->invoke($stb),'');

        $wimResult = array(
            'result' => array(
                'status' => 'success'
            ),
            'data' => array(
                'wim_check_flg' => '1',
                'test' => '1'
            )
        );

        // case 9
        $stb = $this->getMock('all_resource',array( '_getTenant', '_execMultiApi', '_getContInfoTenant', 'success' ));
        $stb->expects($this->any())->method('_getTenant')->will($this->returnValue('1234'));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnValue($execList));
        $stb->expects($this->any())->method('_getContInfoTenant')->will($this->returnValue($countInfo));
        $stb->expects($this->any())->method('success')->will($this->returnArgument(0));
        $stb->_p['IaaS_tenant_id'] = '1234';
        $this->assertEquals( $method->invoke($stb),'');
    }

    /**
     * @covers all_resource::_getContInfoTenant
     * @todo   Implement testGetContInfoTenant().
     */
    public function testGetContInfoTenant(){

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'all_resource';
        $_SERVER['REQUEST_URI']    = '/test/resource';

        $ret = new all_resource();
        $method = new ReflectionMethod( $ret, '_getContInfoTenant' );
        $method->setAccessible( true );

        $execList = array(
            'test' => 'test'
        );

        $stb = $this->getMock('all_resource',array( '_getContractCntLicense', '_getUseCntLicense', '_getContractCntPnf', '_getUseCntPnf', '_getContractCntGlobalip', '_getUseCntGlobalip' ));
        $stb->expects($this->any())->method('_getContractCntLicense')->will($this->returnValue(array(30,array('test1' => '10'))));
        $stb->expects($this->any())->method('_getUseCntLicense')->will($this->returnValue(array(10,array('test1' => '10'))));
        $stb->expects($this->any())->method('_getContractCntPnf')->will($this->returnValue(50));
        $stb->expects($this->any())->method('_getUseCntPnf')->will($this->returnValue(30));
        $stb->expects($this->any())->method('_getContractCntGlobalip')->will($this->returnValue(5));
        $stb->expects($this->any())->method('_getUseCntGlobalip')->will($this->returnValue(2));
        $stb->_p['IaaS_tenant_id'] = '1234';

        $info = array(
            'contract_kind' => 2,
            'function_type'    => 'license',
            'apl_type'         => 1,
            'type'             => 1,
            'device_type'      => 1,
            'redundant_configuration_flg' => '',
            'contract_cnt'     => 30,
            'use_cnt'          => 10,
        );

        // case 1
        $result = $method->invoke($stb, $execList);
        $this->assertEquals( $result['contract_info'][0], $info);
    }

    /**
     * @covers all_resource::_getContInfo
     * @todo   Implement testGetContInfo().
     */
    public function testGetContInfo(){

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'all_resource';
        $_SERVER['REQUEST_URI']    = '/test/resource';

        $ret = new all_resource();
        $method = new ReflectionMethod( $ret, '_getContInfo' );
        $method->setAccessible( true );

        $execList = array(
            'oepnstack_info' => array(
                '0' => array(
                    'vcpus' => array(
                        'quota'   => 10,
                        'use_cnt' => 9,
                        'contract_cnt' => 10,
                    ),
                    'disk' => array(
                        'quota'   => 16800,
                        'use_cnt' => 16000,
                        'contract_cnt' => 5000,
                    ),
                    'ram' => array(
                        'quota'   => 7000,
                        'use_cnt' => 6500,
                        'contract_cnt' => 700,
                    )
                )
            ),
        );

        $stb = $this->getMock('all_resource',
        array(
            '_getThreshold',
            '_getQuotaLisence',
            '_getContractCntLicense',
            '_getUseCntLicense',
            '_getUnavailableCntLicense',
            '_getQuotaPnf',
            '_getContractCntPnf',
            '_getUseCntPnf',
            '_getUnavailableCntPnf',
            '_getQuotaGlobalip',
            '_getContractCntGlobalip',
            '_getUseCntGlobalip',
            '_getUnavailableCntGlobalip',
            '_getQuotaMsa',
            '_getContractCntMsa',
            '_getUseCntMsa',
            '_getUnavailableCntMsa',
            '_getQuotaWan',
            '_getContractCntWan',
            '_getUseCntWan',
            '_getUnavailableCntWan'
        ));
        $stb->expects($this->any())->method('_getThreshold')->will($this->returnValue(80));
        $stb->expects($this->any())->method('_getQuotaLisence')->will($this->returnValue(50));
        $stb->expects($this->any())->method('_getContractCntLicense')->will($this->returnValue(array(30,array('test1' => '10'))));
        $stb->expects($this->any())->method('_getUseCntLicense')->will($this->returnValue(array(10,array('test1' => '10'))));
        $stb->expects($this->any())->method('_getUnavailableCntLicense')->will($this->returnValue(50));
        $stb->expects($this->any())->method('_getQuotaPnf')->will($this->returnValue(50));
        $stb->expects($this->any())->method('_getContractCntPnf')->will($this->returnValue(50));
        $stb->expects($this->any())->method('_getUseCntPnf')->will($this->returnValue(30));
        $stb->expects($this->any())->method('_getUnavailableCntPnf')->will($this->returnValue(30));
        $stb->expects($this->any())->method('_getQuotaGlobalip')->will($this->returnValue(5));
        $stb->expects($this->any())->method('_getContractCntGlobalip')->will($this->returnValue(5));
        $stb->expects($this->any())->method('_getUseCntGlobalip')->will($this->returnValue(4));
        $stb->expects($this->any())->method('_getUnavailableCntGlobalip')->will($this->returnValue(2));
        $stb->expects($this->any())->method('_getQuotaMsa')->will($this->returnValue(2));
        $stb->expects($this->any())->method('_getContractCntMsa')->will($this->returnValue(2));
        $stb->expects($this->any())->method('_getUseCntMsa')->will($this->returnValue(2));
        $stb->expects($this->any())->method('_getUnavailableCntMsa')->will($this->returnValue(2));
        $stb->expects($this->any())->method('_getQuotaWan')->will($this->returnValue(2));
        $stb->expects($this->any())->method('_getContractCntWan')->will($this->returnValue(2));
        $stb->expects($this->any())->method('_getUseCntWan')->will($this->returnValue(2));
        $stb->expects($this->any())->method('_getUnavailableCntWan')->will($this->returnValue(2));

        $info = array(
            'nw_resource_kind' => 2,
            'function_type'    => 'license',
            'quota'            => 50,
            'apl_type'         => 1,
            'threshold'        => 80,
            'type'             => 1,
            'device_type'      => 1,
            'type_detail'      => '',
            'redundant_configuration_flg' => '',
            'contract_cnt'     => 30,
            'unavailable_cnt'  => 50,
            'use_cnt'          => 10,
            'warning_flg'      => 1,
        );

        $result = $method->invoke($stb, $execList);
        $this->assertEquals( $result['contract_info'][0], $info);
    }

    /**
     * @covers all_resource::_getFlavorListForCnt
     * @todo   Implement testGetFlavorListForCnt().
     */
    public function testGetFlavorListForCnt()
    {
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'all_resource';
        $_GET['scenario']          = 'resource';

        $ret = new all_resource();
        $method = new ReflectionMethod( $ret, '_getFlavorListForCnt' );
        $method->setAccessible( true );

        $config = array(
            'os_image_and_flavor_name_list'=> array (
                '1'=> array (
                    '1'=> array (
                        'flavor_name'=>'intersecvm_sg-v4.1-M4D30E0S0C2F1.0P1',
                        'image_name'=>'intersecvm_sg-v4.1',
                    ),
                    '2'=> array (
                        'flavor_name'=>'fortigate_vm-5.2.4-M1D30E0S0C1F1.0P1',
                        'image_name'=>'fortigate_vm-5.2.4',
                    ),
                    '3'=> array (
                        'flavor_name'=>'paloalto_vm-7.0.5-M4D40E0S0C2F1.0P1',
                        'image_name'=>'paloalto_vm-7.0.5',
                    ),
                    '4'=> array (
                        'flavor_name'=>'intersecvm_sg-v4.1-M4D30E0S0C2F1.0P1',
                        'image_name'=>'intersecvm_sg-v4.1',
                    ),
                    '5'=> array (
                        'flavor_name'=>'',
                        'image_name'=>'',
                    ),
                ),
                '2'=> array (
                    '1'=> array (
                        'flavor_name'=>'intersecvm_lb-4.0-M16D50E0S0C2F1.0P1',
                        'image_name'=>'intersecvm_lb-4.0',
                      ),
                    '2'=> array (
                        'flavor_name'=>'big_ip_ve-12.0.0.0.0.606-M4D139E0S0C2F1.0P1',
                        'image_name'=>'big_ip-12.0.0.0.0.606',
                    ),
                    '3'=> array (
                        'flavor_name'=>'vthunder-4.0.1-M2D8E0S0C1F1.0P1',
                        'image_name'=>'vthunder-4.0.1',
                    ),
                ),
                '3'=> array (
                    '1'=> array (
                        'flavor_name'=>'vsrx-12.1x47_d20.7-M2D2E0S0C2F1.0P1',
                        'image_name'=>'vsrx-12.1x47_d20.7',
                    ),
                    '2'=> array (
                        'flavor_name'=>'csr1000v-03.17.01-M4D8E0S0C4F1.0P1',
                        'image_name'=>'csr1000v-03.17.01',
                    ),
                ),
            )
        );

        $confInfo[0]['config_info'] = json_encode( $config );

        $flavorCnt = array(
            'flavors' => array(
                '0' => array(
                    'name'  => 'intersecvm_sg-v4.1-M4D30E0S0C2F1.0P1',
                    'vcpus' => '1',
                    'disk'  => '2',
                    'ram'   => '3000',
                ),
                '1' => array(
                    'name'  => 'intersecvm_lb-4.0-M16D50E0S0C2F1.0P1',
                    'vcpus' => '2',
                    'disk'  => '3',
                    'ram'   => '4000',
                ),
                '2' => array(
                    'name'  => 'vthunder-4.0.1-M2D8E0S0C1F1.0P1',
                    'vcpus' => '3',
                    'disk'  => '4',
                    'ram'   => '5000',
                ),
            ),
        );

        // dummy data Endpoint
        $endpoint_info['endpoint']           = 'http://10.58.70.89:5000/v2.0';
        $endpoint_info['user_id']            = 'admin';
        $endpoint_info['user_password']      = 'admin';
        $endpoint_info['user_key']           = '0fba6fb2f1cf40d68928aafd39e981d1';
        $endpoint_info['role_id']            = '9715c36ef48c44d0ad4bca16d863cc25';
        $endpoint_info['admin_tenant_name']  = 'admin';

        $retData[0]['endpoint_info'] = json_encode( $endpoint_info );

        $result = array(
            '1'=> array(
                '1' => array(
                    'vcpus_count' => '1',
                    'ram_count'   => '3000',
                    'disk_count'  => '2',
                ),
                '4' => array(
                    'vcpus_count' => '1',
                    'ram_count'   => '3000',
                    'disk_count'  => '2',
                ),
            ),
            '2'=> array(
                '1' => array(
                    'vcpus_count' => '2',
                    'ram_count'   => '4000',
                    'disk_count'  => '3',
                ),
                '3' => array(
                    'vcpus_count' => '3',
                    'ram_count'   => '5000',
                    'disk_count'  => '4',
                ),
            ),
        );

        // case 1
        $stb = $this->getMock('all_resource',array( 'getConfig', 'listFlavorsDetail'));
        $stb->expects($this->any())->method('getConfig')->will($this->returnValue( $confInfo ));
        $stb->expects($this->any())->method('listFlavorsDetail')->will($this->returnValue($flavorCnt));
        $this->assertEquals( $method->invoke($stb, 'pod0001', $retData), $result);

        // case 2
        $stb = $this->getMock('all_resource',array( 'getConfig', 'listFlavorsDetail'));
        $stb->expects($this->any())->method('getConfig')->will($this->returnValue(array()));
        $this->assertEquals( $method->invoke($stb, 'pod0001', $retData), array());

    }

    /**
     * @covers all_resource::setFlavorData
     * @todo   Implement testSetFlavorData().
     */
    public function testSetFlavorData()
    {
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'all_resource';
        $_GET['scenario']          = 'resource';
        $_GET['type_detail']       = '3';

        $ret = new all_resource();
        $method = new ReflectionMethod( $ret, 'setFlavorData' );
        $method->setAccessible( true );

        $config = array(
            'os_image_and_flavor_name_list'=> array (
                '1'=> array (
                    '1'=> array (
                        'flavor_name'=>'intersecvm_sg-v4.1-M4D30E0S0C2F1.0P1',
                        'image_name'=>'intersecvm_sg-v4.1',
                    ),
                    '2'=> array (
                        'flavor_name'=>'fortigate_vm-5.2.4-M1D30E0S0C1F1.0P1',
                        'image_name'=>'fortigate_vm-5.2.4',
                    ),
                    '3'=> array (
                        'flavor_name'=>'paloalto_vm-7.0.5-M4D40E0S0C2F1.0P1',
                        'image_name'=>'paloalto_vm-7.0.5',
                    ),
                    '4'=> array (
                        'flavor_name'=>'intersecvm_sg-v4.1-M4D30E0S0C2F1.0P1',
                        'image_name'=>'intersecvm_sg-v4.1',
                    ),
                    '5'=> array (
                        'flavor_name'=>'',
                        'image_name'=>'',
                    ),
                ),
                '2'=> array (
                    '1'=> array (
                        'flavor_name'=>'intersecvm_lb-4.0-M16D50E0S0C2F1.0P1',
                        'image_name'=>'intersecvm_lb-4.0',
                      ),
                    '2'=> array (
                        'flavor_name'=>'big_ip_ve-12.0.0.0.0.606-M4D139E0S0C2F1.0P1',
                        'image_name'=>'big_ip-12.0.0.0.0.606',
                    ),
                    '3'=> array (
                        'flavor_name'=>'vthunder-4.0.1-M2D8E0S0C1F1.0P1',
                        'image_name'=>'vthunder-4.0.1',
                    ),
                ),
                '3'=> array (
                    '1'=> array (
                        'flavor_name'=>'vsrx-12.1x47_d20.7-M2D2E0S0C2F1.0P1',
                        'image_name'=>'vsrx-12.1x47_d20.7',
                    ),
                    '2'=> array (
                        'flavor_name'=>'csr1000v-03.17.01-M4D8E0S0C4F1.0P1',
                        'image_name'=>'csr1000v-03.17.01',
                    ),
                ),
            )
        );

        $flavorCnt = array(
            'flavors' => array(
                '0' => array(
                    'name'  => 'intersecvm_sg-v4.1-M4D30E0S0C2F1.0P1',
                    'vcpus' => '1',
                    'disk'  => '2000',
                    'ram'   => '500',
                ),
                '1' => array(
                    'name'  => 'intersecvm_lb-4.0-M16D50E0S0C2F1.0P1',
                    'vcpus' => '2',
                    'disk'  => '3000',
                    'ram'   => '600',
                ),
                '2' => array(
                    'name'  => 'vthunder-4.0.1-M2D8E0S0C1F1.0P1',
                    'vcpus' => '3',
                    'disk'  => '4000',
                    'ram'   => '700',
                ),
            ),
        );

        $result = array();
        $result[1][1]['vcpus_count'] = '1';
        $result[1][4]['vcpus_count'] = '1';
        $result[2][1]['vcpus_count'] = '2';
        $result[2][3]['vcpus_count'] = '3';
        $result[1][1]['ram_count'] = '500';
        $result[1][4]['ram_count'] = '500';
        $result[2][1]['ram_count'] = '600';
        $result[2][3]['ram_count'] = '700';
        $result[1][1]['disk_count'] = '2000';
        $result[1][4]['disk_count'] = '2000';
        $result[2][1]['disk_count'] = '3000';
        $result[2][3]['disk_count'] = '4000';

        // case 1
        $this->assertEquals( $method->invoke($ret, $config['os_image_and_flavor_name_list'], $flavorCnt ), $result);

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'all_resource';
        $_GET['scenario']          = 'resource';
        $_GET['type_detail']       = '2';

        $flavorCnt = array(
            'flavors' => array(
                '0' => array(
                    'name'  => 'csr1000v-03.17.01-M4D8E0S0C4F1.0P1',
                    'vcpus' => '3',
                    'disk'  => '300',
                    'ram'   => '500',
                ),
                '1' => array(
                    'name'  => 'intersecvm_lb-4.0-M16D50E0S0C2F1.0P1',
                    'vcpus' => '2',
                    'disk'  => '3000',
                    'ram'   => '600',
                ),
                '2' => array(
                    'name'  => 'vthunder-4.0.1-M2D8E0S0C1F1.0P1',
                    'vcpus' => '3',
                    'disk'  => '4000',
                    'ram'   => '700',
                ),
            ),
        );

        $result = array();
        $result[3][2]['vcpus_count'] = '3';
        $result[3][2]['ram_count']   = '500';
        $result[3][2]['disk_count']  = '300';

        // case 2
        $ret->_nalConf['api_type'] = 'wim';
        $this->assertEquals( $method->invoke($ret, $config['os_image_and_flavor_name_list'], $flavorCnt ), $result);


    }

    /**
     * @covers all_resource::_execResult
     * @todo   Implement testExecResult().
     */
    public function testExecResult()
    {
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type'] = 'resource';
        $_SERVER['REQUEST_URI'] = "/Nal/resource/";
        $ret = new all_resource();
        $method = new ReflectionMethod($ret, '_execResult');
        $method->setAccessible(true);

        $url = 'http://127.0.0.1/Nal/';

        // case 1
        $err = array();
        $this->assertEquals($method->invoke($ret,$err,$url),'');

        // case 2
        $err['result'] = array( 'error-code' => 'NAL100000', 'message' => '' );
        try{
            $method->invoke($ret,$err,$url);
        }catch(Exception $e){
            $this->assertEquals('',$e->getMessage());
        }

        // case 3
        $err['result'] = array( 'error-code' => 'NAL140001', 'message' => 'test' );
        try{
            $method->invoke($ret,$err,$url);
        }catch(Exception $e){
            $this->assertEquals('test',$e->getMessage());
        }
    }

    /**
     * @covers all_resource::_getOpenStackCnt
     * @todo   Implement testGetOpenStackCnt().
     */
    public function testGetOpenStackCnt()
    {
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'all_resource';
        $_GET['scenario']          = 'resource';
        $_SERVER['REQUEST_URI']    = '/test/resource';

        $ret = new all_resource();
        $method = new ReflectionMethod( $ret, '_getOpenStackCnt' );
        $method->setAccessible( true );

        $execList = array(
            'pod_info' => array(
                '0' => array(
                    'pod_id'   => 'pod0001',
                    'ID'       => '0',
                    'use_type' => '1'
                ),
                '1' => array(
                    'pod_id'   => 'pod0002',
                    'ID'       => '1',
                    'use_type' => '2'
                ),
                '2' => array(
                    'pod_id'   => 'pod0003',
                    'ID'       => '2',
                    'use_type' => '1'
                ),
            ),
            'apl_info' => array(
                '0' => array(
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID'             => '1',
                    'node_id'        => '1234',
                ),
                '1' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '2',
                    'node_id'        => '2345',
                ),
                '2' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '2',
                    'node_id'        => '3456',
                )
            )
        );

        $flavorListForCnt[1][1]['count'] = '1';
        $flavorListForCnt[1][4]['count'] = '1';
        $flavorListForCnt[2][1]['count'] = '2';
        $flavorListForCnt[2][3]['count'] = '3';

        $info = array(
            'vcpus' => array( 'quota' => '40' ),
            'disk' => array( 'quota' => '16800' ),
            'ram' => array( 'quota' => '7000' ),
            'use_info' => array(
                '1234' => array(
                    'vcpus' => 10,
                    'ram'   => 1000,
                    'disk'  => 700,
                ),
                '2345' => array(
                    'vcpus' => 10,
                    'ram'   => 1000,
                    'disk'  => 800,
                )
            )
        );

        $wimResult = array(
            'result' => array(
                'status' => 'success'
            ),
            'data' => array(
                'vcpus' => array( 'quota' => '10' ),
                'disk' => array( 'quota' => '16000' ),
                'ram' => array( 'quota' => '5000' ),
                'use_info' => array(
                    '1234' => array(
                        'vcpus' => 10,
                        'ram'   => 1000,
                        'disk'  => 700,
                    ),
                    '2345' => array(
                        'vcpus' => 10,
                        'ram'   => 1100,
                        'disk'  => 1500,
                    )
                )
            )
        );

        $result = array(
            '1' => array(
                'vcpus' => array(
                    'quota' => 20,
                    'use_cnt' => 6,
                    'contract_cnt' => 10,
                ),
                'disk' => array(
                    'quota' => 32000,
                    'use_cnt' => 2000,
                    'contract_cnt' => 10000,
                ),
                'ram' => array(
                    'quota' => 10000,
                    'use_cnt' => 800,
                    'contract_cnt' => 8000,
                )
            ),
            '2' => array(
                'vcpus' => array(
                    'quota' => 10,
                    'use_cnt' => 3,
                    'contract_cnt' => 5,
                ),
                'disk' => array(
                    'quota' => 16000,
                    'use_cnt' => 1000,
                    'contract_cnt' => 5000,
                ),
                'ram' => array(
                    'quota' => 5000,
                    'use_cnt' => 400,
                    'contract_cnt' => 4000,
                )
            )
        );

        $oepnStackInfo = array(
            'vcpus' => array(
                'quota' => 10,
                'use_cnt' => 3,
                'contract_cnt' => 5,
            ),
            'disk' => array(
                'quota' => 16000,
                'use_cnt' => 1000,
                'contract_cnt' => 5000,
            ),
            'ram' => array(
                'quota' => 5000,
                'use_cnt' => 400,
                'contract_cnt' => 4000,
            ),
        );

        // case 1
        $stb = $this->getMock('all_resource',array( '_execApi', '_execProcess', '_getOepnStackInfo'));
        $stb->expects($this->any())->method('_execApi')->will($this->returnValue($wimResult));
        $stb->expects($this->any())->method('_execProcess')->will($this->returnValue($info));
        $stb->expects($this->any())->method('_getOepnStackInfo')->will($this->returnValue($oepnStackInfo));
        $this->assertEquals( $method->invoke($stb, $execList),$result);

        $execList = array(
            'pod_info' => array(
                '0' => array(
                    'pod_id'   => 'pod0002',
                    'ID'       => '1',
                    'use_type' => '2'
                ),
            )
        );

        $wimResult = array(
            'result' => array(
                'status' => 'error',
                'error-code' => 'NAL110001',
                'message' => 'wim error'
            ),
            'data' => array(
            )
        );

        // case 2
        $stb = $this->getMock('all_resource',array( '_execApi' ));
        $stb->expects($this->any())->method('_execApi')->will($this->returnValue($wimResult));

        try {
            $method->invoke($stb,$execList);
        }catch( Exception $e){
            $this->assertEquals($e->getMessage(),'wim error');
        }

    }

    /**
     * @covers all_resource::_execProcess
     * @todo   Implement testExecProcess().
     */
    public function testExecProcess()
    {
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'all_resource';
        $_GET['scenario']          = 'resource';
        $_GET['type_detail']       = '3';

        $ret = new all_resource();
        $method = new ReflectionMethod( $ret, '_execProcess' );
        $method->setAccessible( true );

        // dummy data Endpoint
        $endpoint_info['endpoint']           = 'http://10.58.70.89:5000/v2.0';
        $endpoint_info['user_id']            = 'admin';
        $endpoint_info['user_password']      = 'admin';
        $endpoint_info['user_key']           = '0fba6fb2f1cf40d68928aafd39e981d1';
        $endpoint_info['role_id']            = '9715c36ef48c44d0ad4bca16d863cc25';
        $endpoint_info['admin_tenant_name']  = 'admin';

        $retData[0]['endpoint_info'] = json_encode( $endpoint_info );

        $listUsage = '{"tenant_usages":[{"server_usages":[{"ended_at":null,"flavor":"csr1000v-03.17.01-M4D8E0S0C4F1.0P1","hours":4.444444444444445e-08,"instance_id":"93f13f83-863b-47f1-a7a3-e0c1757313cb","local_gb":1,"memory_mb":512,"name":"T00024dc01ce01","started_at":"2016-10-20T07:12:40.000000","state":"stopped","tenant_id":"f711f1db1f014d589234cdb5010c39e4","uptime":2346499,"vcpus":1},],"start":"2016-11-16T11:00:59.696802","stop":"2016-11-16T11:00:59.696818","tenant_id":"f711f1db1f014d589234cdb5010c39e4","total_hours":1.3333333333333334e-07,"total_local_gb_usage":1000,"total_memory_mb_usage":8000,"total_vcpus_usage":1},{"server_usages":[{"ended_at":null,"flavor":"fortigate_vm-5.2.4-M1D30E0S0C1F1.0P1","hours":4.444444444444445e-08,"instance_id":"5d0d083b-82b6-471c-9808-717824a39254","local_gb":1,"memory_mb":512,"name":"nal_vfw_20_fort01","started_at":"2016-10-21T00:39:05.000000","state":"stopped","tenant_id":"ee60e6eccc0e458daff42a6ec39ad9c0","uptime":2283714,"vcpus":1},],"start":"2016-11-16T11:00:59.696802","stop":"2016-11-16T11:00:59.696818","tenant_id":"ee60e6eccc0e458daff42a6ec39ad9c0","total_hours":1.3333333333333334e-07,"total_local_gb_usage":500,"total_memory_mb_usage":3000,"total_vcpus_usage":1},}]}';

        $hostDetail = array(
            '0' => array(
                'cpu' => 1,
                'disk_gb' => 1000,
                'memory_mb' => 8200,
            )
        );

        $flavorListForCnt[1][1]['vcpus_count'] = '1';
        $flavorListForCnt[1][1]['ram_count']   = '3000';
        $flavorListForCnt[1][1]['disk_count']  = '2';
        $flavorListForCnt[1][4]['vcpus_count'] = '1';
        $flavorListForCnt[1][4]['ram_count']   = '3000';
        $flavorListForCnt[1][4]['disk_count']  = '2';
        $flavorListForCnt[2][1]['vcpus_count'] = '2';
        $flavorListForCnt[2][1]['ram_count']   = '4000';
        $flavorListForCnt[2][1]['disk_count']  = '3';
        $flavorListForCnt[2][3]['vcpus_count'] = '3';
        $flavorListForCnt[2][3]['ram_count']   = '5000';
        $flavorListForCnt[2][3]['disk_count']  = '4';

        $setData = array(
            'quota' => '10',
            'use_cnt' => '5',
            'flavor_list_for_cnt' => $flavorListForCnt,
        );

        $result = array();
        $result = $setData;
        // case 1
        $stb = $this->getMock('all_resource',array( 'getEndpoint', 'listUsageReport', 'listHostDetail', '_getFlavorListForCnt','setData'));
        $stb->expects($this->any())->method('getEndpoint')->will($this->returnValue($retData));
        $stb->expects($this->any())->method('listUsageReport')->will($this->returnValue(json_decode( $listUsage, true )));
        $stb->expects($this->any())->method('listHostDetail')->will($this->returnValue($hostDetail));
        $stb->expects($this->any())->method('_getFlavorListForCnt')->will($this->returnValue($flavorListForCnt));
        $stb->expects($this->any())->method('setData')->will($this->returnValue($setData));
        $this->assertEquals( $method->invoke($stb, 'pod0001', '3'),$result);

        // case 2
        $stb = $this->getMock('all_resource',array( 'getEndpoint'));
        $stb->expects($this->any())->method('getEndpoint')->will($this->returnValue(array()));
        $this->assertEquals( $method->invoke($stb, 'pod0001', '3'),array());

        // case 3
        $stb = $this->getMock('all_resource',array( 'getEndpoint', 'listUsageReport', 'listHostDetail', '_getFlavorListForCnt', 'setData'));
        $stb->expects($this->any())->method('getEndpoint')->will($this->returnValue($retData));
        $stb->expects($this->any())->method('listUsageReport')->will($this->returnValue(json_decode( $listUsage, true )));
        $stb->expects($this->any())->method('listHostDetail')->will($this->returnValue($hostDetail));
        $stb->expects($this->any())->method('_getFlavorListForCnt')->will($this->returnValue($flavorListForCnt));
        $stb->expects($this->any())->method('setData')->will($this->returnValue($setData));
        $stb->_nalConf['api_type'] = 'wim'; // Wim
        $this->assertEquals( $method->invoke($stb, 'pod0001', '2'),$result);

    }

    /**
     * @covers all_resource::setData
     * @todo   Implement testSetData().
     */
    public function testSetData()
    {
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'all_resource';
        $_GET['scenario']          = 'resource';
        $_GET['type_detail']       = '3';

        $usagesInfo = array(
            'tenant_usages' => array(
                '0' => array(
                    'tenant_id' => '1234',
                    'server_usages' => array(
                        '0' => array(
                            'instance_id' => '1234',
                            'vcpus'     => 1,
                            'memory_mb' => 8000,
                            'local_gb'  => 1000
                        ),
                        '1' => array(
                            'instance_id' => '2345',
                            'vcpus'     => 1,
                            'memory_mb' => 7000,
                            'local_gb'  => 900
                        ),
                   ),
               ),
            )
        );
        $hostDetail = array(
            '0' => array(
                'cpu' => 1,
                'disk_gb' => 2000,
                'memory_mb' => 8200,
            ),
            '1' => array(
                'cpu' => 2,
                'disk_gb' => 2000,
                'memory_mb' => 8200,
            )
        );

        $ret = new all_resource();
        $method = new ReflectionMethod( $ret, 'setData' );
        $method->setAccessible( true );

        $setData = array(
            'vcpus' => array( 'quota' => '3' ),
            'ram' => array( 'quota' => '16400' ),
            'disk' => array( 'quota' => '4000' ),
            'use_info' => array(
                '1234' => array(
                    'vcpus' => '1',
                    'ram'   => '8000',
                    'disk'  => '1000',
                ),
                '2345' => array(
                    'vcpus' => '1',
                    'ram'   => '7000',
                    'disk'  => '900',
                )
            )
        );

        // case 1
        $this->assertEquals( $method->invoke($ret, $usagesInfo, $hostDetail ),$setData);

    }

    /**
     * @covers all_resource::setWarningFlg
     * @todo   Implement testSetWarningFlg().
     */
    public function testSetWarningFlg(){

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'all_resource';
        $_GET['scenario']          = 'resource';

        $ret = new all_resource();
        $method = new ReflectionMethod( $ret, 'setWarningFlg' );
        $method->setAccessible( true );

        // case 1
        $this->assertEquals( $method->invoke($ret, 100, 10, 50, 80 ),0);

        // case 2
        $this->assertEquals( $method->invoke($ret, 100, 90, '', 85 ), 1);

        // case 3
        $this->assertEquals( $method->invoke($ret, 100, 50, 30, 79 ), 1);

        // case 4
        $this->assertEquals( $method->invoke($ret, 100, 0, 0, 70 ), 0);

        // case 5
        $this->assertEquals( $method->invoke($ret, 0, 20, 50, 70 ), 0);
    }

    /**
     * @covers all_resource::_getOepnStackInfo
     * @todo   Implement testGetOepnStackInfo().
     */
    public function testGetOepnStackInfo()
    {
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'all_resource';
        $_GET['scenario']          = 'resource';

        $ret = new all_resource();
        $method = new ReflectionMethod( $ret, '_getOepnStackInfo' );
        $method->setAccessible( true );

        $execList = array(
            'apl_info' => array(
                '0' => array(
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID'             => '1',
                    'node_id'        => '1234',
                ),
                '1' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '2',
                    'node_id'        => '2345',
                ),
                '2' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '3',
                    'node_id'        => '3456',
                ),
                '3' => array(
                    'tenant_name'    => 'tenant3',
                    'IaaS_tenant_id' => '3456',
                    'ID'             => '4',
                    'node_id'        => '5555',
                )
            ),
            'tenant_contract_info' => array(
                '0' => array(
                    'apl_type'       => 1,
                    'type'           => 1,
                    'device_type'    => 1,
                    'contract'       => '2',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 2,
                ),
                '1' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 1,
                    'contract'    => '4',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 3,
                ),
                '2' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 3,
                    'contract'    => '6',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 4,
                ),
                '3' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 3,
                    'contract'    => '6',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID' => 5,
                ),
                '4' => array(
                    'apl_type'    => 1,
                    'type'        => 3,
                    'device_type' => 2,
                    'contract'    => '1',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID' => 6,
                ),
                '5' => array(
                    'apl_type'    => 2,
                    'type'        => 1,
                    'device_type' => 2,
                    'contract'    => '1',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID' => 7,
                ),
            )
        );

        $flavorListForCnt[1][1]['vcpus_count'] = '1';
        $flavorListForCnt[1][1]['ram_count']   = '3000';
        $flavorListForCnt[1][1]['disk_count']  = '2';
        $flavorListForCnt[1][4]['vcpus_count'] = '1';
        $flavorListForCnt[1][4]['ram_count']   = '3000';
        $flavorListForCnt[1][4]['disk_count']  = '2';
        $flavorListForCnt[2][1]['vcpus_count'] = '2';
        $flavorListForCnt[2][1]['ram_count']   = '4000';
        $flavorListForCnt[2][1]['disk_count']  = '3';
        $flavorListForCnt[2][3]['vcpus_count'] = '3';
        $flavorListForCnt[2][3]['ram_count']   = '5000';
        $flavorListForCnt[2][3]['disk_count']  = '4';

        $flavorListForCntWim[3][2]['vcpus_count'] = '30';
        $flavorListForCntWim[3][2]['ram_count']   = '6000';
        $flavorListForCntWim[3][2]['disk_count']  = '20';

        $nalData = array(
            'vcpus' => array( 'quota' => '60' ),
            'ram'   => array( 'quota' => '6000' ),
            'disk'  => array( 'quota' => '4000' ),
            'use_info' => array(
                '1234' => array(
                    'vcpus' => '900',
                    'ram'   => '2000',
                    'disk'  => '500',
                ),
                '2345' => array(
                    'vcpus' => '1000',
                    'ram'   => '2000',
                    'disk'  => '400',
                ),
                'aaaa' => array(
                    'vcpus' => '900',
                    'ram'   => '2000',
                    'disk'  => '500',
                ),
            ),
            'flavor_list_for_cnt' => $flavorListForCnt,
        );

        $wimData = array(
            'wim_check_flg' => 1,
            'flavor_list_for_cnt' => $flavorListForCntWim,
        );

        $result = array(
            'vcpus' => array(
                'quota'        => '60',
                'use_cnt'      => '1900',
                'contract_cnt' => '46',
            ),
            'ram' => array(
                'quota'        => '6000',
                'use_cnt'      => '4000',
                'contract_cnt' => '82000',
            ),
            'disk' => array(
                'quota'        => '4000',
                'use_cnt'      => '900',
                'contract_cnt' => '64',
            ),
        );

        // case 1
        $this->assertEquals( $method->invoke($ret, $nalData, $wimData, $execList, '1'), $result);

        $execList = array(
            'apl_info' => array(
                '0' => array(
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID'             => '1',
                    'node_id'        => '1234',
                ),
                '1' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '2',
                    'node_id'        => '2345',
                ),
                '2' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '3',
                    'node_id'        => '3456',
                ),
                '3' => array(
                    'tenant_name'    => 'tenant3',
                    'IaaS_tenant_id' => '3456',
                    'ID'             => '4',
                    'node_id'        => '5555',
                )
            ),
            'tenant_contract_info' => array(
                '0' => array(
                    'apl_type'       => 1,
                    'type'           => 1,
                    'device_type'    => 1,
                    'contract'       => '2',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 2,
                ),
                '1' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 1,
                    'contract'    => '4',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 3,
                ),
                '2' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 3,
                    'contract'    => '6',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 4,
                ),
                '3' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 3,
                    'contract'    => '6',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID' => 5,
                ),
                '4' => array(
                    'apl_type'    => 1,
                    'type'        => 3,
                    'device_type' => 2,
                    'contract'    => '1',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID' => 6,
                ),
                '5' => array(
                    'apl_type'    => 1,
                    'type'        => 1,
                    'device_type' => 1,
                    'contract'    => '10',
                    'tenant_name'    => 'tenant4',
                    'IaaS_tenant_id' => '4567',
                    'ID' => 6,
                ),
            )
        );

        $nalData = array(
            'vcpus' => array( 'quota' => '60' ),
            'ram'   => array( 'quota' => '6000' ),
            'disk'  => array( 'quota' => '4000' ),
            'use_info' => array(
                '1234' => array(
                    'vcpus' => '900',
                    'ram'   => '2000',
                    'disk'  => '500',
                ),
                '2345' => array(
                    'vcpus' => '1000',
                    'ram'   => '2000',
                    'disk'  => '500',
                ),
                '5555' => array(
                    'vcpus' => '1000',
                    'ram'   => '2000',
                    'disk'  => '500',
                ),
            ),
            'flavor_list_for_cnt' => $flavorListForCnt,
        );

        $wimData = array(
            'wim_check_flg' => 1,
            'flavor_list_for_cnt' => $flavorListForCntWim,
        );

        $result = array(
            'vcpus' => array(
                'quota'        => '60',
                'use_cnt'      => '2900',
                'contract_cnt' => '116',
            ),
            'ram' => array(
                'quota'        => '6000',
                'use_cnt'      => '6000',
                'contract_cnt' => '124000',
            ),
            'disk' => array(
                'quota'        => '4000',
                'use_cnt'      => '1500',
                'contract_cnt' => '124',
            ),
        );

        // case 2
        $this->assertEquals( $method->invoke($ret, $nalData, $wimData, $execList, '3'), $result);

        $nalData = array(
            'vcpus' => array( 'quota' => '60' ),
            'ram'   => array( 'quota' => '6000' ),
            'disk'  => array( 'quota' => '4000' ),
            'use_info' => array(
                '1234' => array(
                    'vcpus' => '900',
                    'ram'   => '2000',
                    'disk'  => '500',
                ),
                '2345' => array(
                    'vcpus' => '1000',
                    'ram'   => '2000',
                    'disk'  => '500',
                ),
                '3456' => array(
                    'vcpus' => '1000',
                    'ram'   => '2000',
                    'disk'  => '500',
                ),
                '5555' => array(
                    'vcpus' => '1000',
                    'ram'   => '2000',
                    'disk'  => '500',
                ),
            ),
            'flavor_list_for_cnt' => $flavorListForCnt,
        );

        $result = array(
            'vcpus' => array(
                'quota'        => '60',
                'use_cnt'      => '3900',
                'contract_cnt' => '56',
            ),
            'ram' => array(
                'quota'        => '6000',
                'use_cnt'      => '8000',
                'contract_cnt' => '112000',
            ),
            'disk' => array(
                'quota'        => '4000',
                'use_cnt'      => '2000',
                'contract_cnt' => '84',
            ),
        );

        // case 3
        $this->assertEquals( $method->invoke($ret, $nalData, $wimData, $execList, '1'), $result);

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'all_resource';
        $_GET['scenario']          = 'resource';

        $ret = new all_resource();
        $method = new ReflectionMethod( $ret, '_getOepnStackInfo' );
        $method->setAccessible( true );

        $flavorListForCnt[1][1]['vcpus_count'] = '1';
        $flavorListForCnt[1][1]['ram_count']   = '3000';
        $flavorListForCnt[1][1]['disk_count']  = '2';
        $flavorListForCnt[1][4]['vcpus_count'] = '1';
        $flavorListForCnt[1][4]['ram_count']   = '3000';
        $flavorListForCnt[1][4]['disk_count']  = '2';
        $flavorListForCnt[2][1]['vcpus_count'] = '2';
        $flavorListForCnt[2][1]['ram_count']   = '4000';
        $flavorListForCnt[2][1]['disk_count']  = '3';
        $flavorListForCnt[2][3]['vcpus_count'] = '3';
        $flavorListForCnt[2][3]['ram_count']   = '5000';
        $flavorListForCnt[2][3]['disk_count']  = '4';

        $flavorListForCntWim[3][2]['vcpus_count'] = '30';
        $flavorListForCntWim[3][2]['ram_count']   = '6000';
        $flavorListForCntWim[3][2]['disk_count']  = '20';

        $nalData = array(
            'flavor_list_for_cnt' => $flavorListForCnt,
        );

        $wimData = array(
            'wim_check_flg' => 1,
            'vcpus' => array( 'quota' => '60' ),
            'ram'   => array( 'quota' => '6000' ),
            'disk'  => array( 'quota' => '4000' ),
            'use_info' => array(
                '1234' => array(
                    'vcpus' => '900',
                    'ram'   => '2000',
                    'disk'  => '500',
                ),
                '2345' => array(
                    'vcpus' => '1000',
                    'ram'   => '2000',
                    'disk'  => '500',
                ),
            ),
            'flavor_list_for_cnt' => $flavorListForCntWim,
        );

        $result = array(
            'vcpus' => array(
                'quota'        => '60',
                'use_cnt'      => '1900',
                'contract_cnt' => '60',
            ),
            'ram' => array(
                'quota'        => '6000',
                'use_cnt'      => '4000',
                'contract_cnt' => '12000',
            ),
            'disk' => array(
                'quota'        => '4000',
                'use_cnt'      => '1000',
                'contract_cnt' => '40',
            ),
        );

        // case 4
        $this->assertEquals( $method->invoke($ret, $nalData, $wimData, $execList, '2'), $result);

        $execList = array(
            'apl_info' => array(
            ),
            'tenant_contract_info' => array(
                '0' => array(
                    'apl_type'       => 1,
                    'type'           => 1,
                    'device_type'    => 1,
                    'contract'       => '2',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 2,
                ),
                '1' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 1,
                    'contract'    => '4',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 3,
                ),
                '2' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 3,
                    'contract'    => '6',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 4,
                ),
                '3' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 3,
                    'contract'    => '6',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID' => 5,
                ),
                '4' => array(
                    'apl_type'    => 1,
                    'type'        => 3,
                    'device_type' => 2,
                    'contract'    => '1',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID' => 6,
                ),
                '5' => array(
                    'apl_type'    => 1,
                    'type'        => 1,
                    'device_type' => 1,
                    'contract'    => '10',
                    'tenant_name'    => 'tenant4',
                    'IaaS_tenant_id' => '4567',
                    'ID' => 6,
                ),
            )
        );

        $nalData = array(
            'vcpus' => array( 'quota' => '60' ),
            'ram'   => array( 'quota' => '6000' ),
            'disk'  => array( 'quota' => '4000' ),
            'use_info' => array(
                '1234' => array(
                    'vcpus' => '900',
                    'ram'   => '2000',
                    'disk'  => '500',
                ),
                '2345' => array(
                    'vcpus' => '1000',
                    'ram'   => '2000',
                    'disk'  => '500',
                ),
                '5555' => array(
                    'vcpus' => '1000',
                    'ram'   => '2000',
                    'disk'  => '500',
                ),
            ),
            'flavor_list_for_cnt' => $flavorListForCnt,
        );

        $wimData = array(
            'wim_check_flg' => 1,
            'flavor_list_for_cnt' => $flavorListForCntWim,
        );

        $result = array(
            'vcpus' => array(
                'quota'        => '60',
                'use_cnt'      => '0',
                'contract_cnt' => '56',
            ),
            'ram' => array(
                'quota'        => '6000',
                'use_cnt'      => '0',
                'contract_cnt' => '112000',
            ),
            'disk' => array(
                'quota'        => '4000',
                'use_cnt'      => '0',
                'contract_cnt' => '84',
            ),
        );

        // case 5
        $this->assertEquals( $method->invoke($ret, $nalData, $wimData, $execList, '1'), $result);

        $execList = array(
            'apl_info' => array(
                '0' => array(
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID'             => '1',
                    'node_id'        => '1234',
                ),
                '1' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '2',
                    'node_id'        => '2345',
                ),
                '2' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '3',
                    'node_id'        => '3456',
                ),
                '3' => array(
                    'tenant_name'    => 'tenant3',
                    'IaaS_tenant_id' => '3456',
                    'ID'             => '4',
                    'node_id'        => '5555',
                )
            ),
            'tenant_contract_info' => array(
            )
        );

        $result = array(
            'vcpus' => array(
                'quota'        => '60',
                'use_cnt'      => '2900',
                'contract_cnt' => '0',
            ),
            'ram' => array(
                'quota'        => '6000',
                'use_cnt'      => '6000',
                'contract_cnt' => '0',
            ),
            'disk' => array(
                'quota'        => '4000',
                'use_cnt'      => '1500',
                'contract_cnt' => '0',
            ),
        );

        // case 6
        $this->assertEquals( $method->invoke($ret, $nalData, $wimData, $execList, '1'), $result);

    }

}
