<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-15 at 12:32:07.
 */

require_once dirname(__FILE__) . '/../Nal/api/app/all_node.php';

class all_nodeTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var all_node
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        if( !defined('PHPUNIT_RUN')) {
            define( 'PHPUNIT_RUN', 1 );
        }
        $this->homeDir = realpath( dirname(__FILE__) ) ;
        if( !defined('HOME_DIR')) {
            define( 'HOME_DIR', $this->homeDir );
        }
        if( !defined('API_DIR')) {
            define( 'API_DIR' , HOME_DIR . '' );
        }
        if( !defined('APP_DIR')) {
            define( 'APP_DIR' , API_DIR . '/Stub' );
        }
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers all_node::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // case 1
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'all_node';
        $_GET['node_id']           = '123456789';
        $_SERVER['REQUEST_URI']    = "/test/node/";

        $ret = new all_node();
        $method = new ReflectionMethod( $ret, 'get' );
        $method->setAccessible( true );

        $stb = $this->getMock('all_node',array('_execApi', 'success'));
        $stb->expects($this->any())->method('_execApi')->will($this->returnArgument(0));
        $stb->expects($this->any())->method('success')->will($this->returnArgument(0));
        $this->assertEquals( $method->invoke($stb),'');

    }

}
