<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-03 at 10:50:16.
 */

require_once dirname(__FILE__) . '/../Nal/api/app/cpu_detail.php';

class cpu_detailTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var cpu_detail
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        if( !defined('PHPUNIT_RUN')) {
            define( 'PHPUNIT_RUN', 1 );
        }
        $this->homeDir = realpath( dirname(__FILE__) ) ;
        if( !defined('HOME_DIR')) {
            define( 'HOME_DIR', $this->homeDir );
        }
        if( !defined('API_DIR')) {
            define( 'API_DIR' , HOME_DIR . '' );
        }
        if( !defined('APP_DIR')) {
            define( 'APP_DIR' , API_DIR . '/Stub' );
        }
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers cpu_detail::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        $_SERVER['REQUEST_URI'] = "/Nal/resource/";
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'cpu_detail';
        $_GET['scenario']          = 'resource';

        $ret = new cpu_detail();
        $method = new ReflectionMethod( $ret, 'get' );
        $method->setAccessible( true );

        // case 1
        try {
            $method->invoke($ret);
        }catch( Exception $e){
            $this->assertEquals($e->getMessage(),'pod_id is not set.');
        }

        $_GET['pod_id'] = 'pod0001';

        $ret = new cpu_detail();
        $method = new ReflectionMethod( $ret, 'get' );
        $method->setAccessible( true );

        // dummy data Pod
        $retPodData[0]['use_type'] = '1';

        $execList = array(
            'pod_info' => array(
                '0' => array(
                    'pod_id'   => 'pod0001',
                    'use_type' => '1',
                ),
            ),
            'apl_info' => array(
                '0' => array(
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID'             => '1',
                    'node_id'        => '1234',
                ),
                '1' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '2',
                    'node_id'        => '2345',
                ),
                '2' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '3',
                    'node_id'        => '3456',
                ),
                '3' => array(
                    'tenant_name'    => 'tenant3',
                    'IaaS_tenant_id' => '3456',
                    'ID'             => '4',
                    'node_id'        => '5555',
                )
            ),
            'tenant_contract_info' => array(
                '0' => array(
                    'apl_type'       => 1,
                    'type'           => 1,
                    'device_type'    => 1,
                    'contract'       => '2',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 2,
                ),
                '1' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 1,
                    'contract'    => '4',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 3,
                ),
                '2' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 3,
                    'contract'    => '6',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 4,
                ),
                '3' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 3,
                    'contract'    => '6',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID' => 5,
                ),
            )
        );

        // dummy data Endpoint
        $endpoint_info['endpoint']           = 'http://10.58.70.89:5000/v2.0';
        $endpoint_info['user_id']            = 'admin';
        $endpoint_info['user_password']      = 'admin';
        $endpoint_info['user_key']           = '0fba6fb2f1cf40d68928aafd39e981d1';
        $endpoint_info['role_id']            = '9715c36ef48c44d0ad4bca16d863cc25';
        $endpoint_info['admin_tenant_name']  = 'admin';

        $retData[0]['endpoint_info'] = json_encode( $endpoint_info );

        $usagesInfo = array(
            'tenant_usages' => array(
                '0' => array(
                    'server_usages' => array(
                        '0' => array(
                            'interfase_id' => '1234',
                            'vcpus'        => 1000,
                            'memory_mb'    => 8000,
                            'local_gb'     => 1
                        ),
                        '1' => array(
                            'interfase_id' => '1234',
                            'vcpus'        => 900,
                            'memory_mb'    => 7000,
                            'local_gb'     => 1
                        ),
                        '2' => array(
                            'interfase_id' => '5555',
                            'vcpus'        => 900,
                            'memory_mb'    => 7000,
                            'local_gb'     => 1
                        ),
                        '3' => array(
                            'interfase_id' => '3456',
                            'vcpus'        => 900,
                            'memory_mb'    => 7000,
                            'local_gb'     => 1
                        ),
                   ),
               ),
            )
        );
        $hostDetail = array(
            '0' => array(
                'cpu' => 1,
                'disk_gb' => 2000,
                'memory_mb' => 8200,
            ),
            '1' => array(
                'cpu' => 2,
                'disk_gb' => 2000,
                'memory_mb' => 8200,
            )
        );

        $flavorListForCnt[1][1]['count'] = '1';
        $flavorListForCnt[1][4]['count'] = '1';
        $flavorListForCnt[2][1]['count'] = '2';
        $flavorListForCnt[2][3]['count'] = '3';

        $wimResult = array(
            'result' => array(
                'status' => 'success'
            ),
            'data' => array(
                'wim_check_flg' => 1,
                'total_count' => array(
                    'quota' => '3',
                    'use_cnt' => '1900',
                ),
                'use_info' => array(
                    '1234' => '900',
                    '2345' => '1000',
                ),
                'flavor_list_for_cnt' => $flavorListForCnt,
            )
        );

        $setData = array(
            'total_count' => array(
                'quota' => '3',
                'use_cnt' => '1900',
            ),
            'use_info' => array(
                '1234' => '1000',
                '2345' => '900',
                '3456' => '900',
                '5555' => '800'
            ),
        );

        $getContInfo = array(
            'total_count' => array(
                'quota' => '3',
                'use_cnt' => '1900',
            ),
            'contract_info' => array(
                '0' => array(
                    'ID'             => '0',
                    'use_cnt'        => '2',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'contract_cnt'   => '5',
                ),
                '1' => array(
                    'ID'             => '1',
                    'use_cnt'        => '3',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'contract_cnt'   => '10',
                ),
            ),
        );

        $wimResultNoData = array(
            'result' => array(
                'status' => 'success'
            ),
            'data' => array(
                'wim_check_flg' => 1,
            )
        );

        // case 2
        $stb = $this->getMock('cpu_detail',array( '_execMultiApi', '_execApi', 'getEndpoint', 'listUsageReport', 'listHostDetail', 'setData', '_getFlavorListForCnt', '_getContInfo', 'success' ));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnValue($execList));
        $stb->expects($this->any())->method('_execApi')->will($this->returnValue($wimResult));
        $stb->expects($this->any())->method('getEndpoint')->will($this->returnValue($retData));
        $stb->expects($this->any())->method('listUsageReport')->will($this->returnValue($usagesInfo));
        $stb->expects($this->any())->method('listHostDetail')->will($this->returnValue($hostDetail));
        $stb->expects($this->any())->method('_getFlavorListForCnt')->will($this->returnValue($flavorListForCnt));
        $stb->expects($this->any())->method('setData')->will($this->returnValue($setData));
        $stb->expects($this->any())->method('_getContInfo')->will($this->returnValue($getContInfo));
        $stb->expects($this->any())->method('success')->will($this->returnArgument(0));
        $this->assertEquals( $method->invoke($stb),'');

        // case 3
        $stb = $this->getMock('cpu_detail',array( '_execMultiApi', '_execApi', 'getEndpoint', 'success' ));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnValue($execList));
        $stb->expects($this->any())->method('_execApi')->will($this->returnValue($wimResultNoData));
        $stb->expects($this->any())->method('getEndpoint')->will($this->returnValue(array()));
        $stb->expects($this->any())->method('success')->will($this->returnArgument(0));
        $this->assertEquals( $method->invoke($stb),'');

        // dummy data Pod
        $execList['pod_info'][0]['use_type'] = 2;

        // case 4
        $stb = $this->getMock('cpu_detail',array( '_execMultiApi', '_execApi', 'getEndpoint', '_getFlavorListForCnt', '_getContInfo', 'setData', 'success' ));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnValue($execList));
        $stb->expects($this->any())->method('_execApi')->will($this->returnValue($wimResult));
        $stb->expects($this->any())->method('getEndpoint')->will($this->returnValue($retData));
        $stb->expects($this->any())->method('_getFlavorListForCnt')->will($this->returnValue($flavorListForCnt));
        $stb->expects($this->any())->method('setData')->will($this->returnValue($setData));
        $stb->expects($this->any())->method('_getContInfo')->will($this->returnValue($getContInfo));
        $stb->expects($this->any())->method('success')->will($this->returnArgument(0));
        $this->assertEquals( $method->invoke($stb),'');

        // case 5
        $stb = $this->getMock('cpu_detail',array( 'getEndpoint', 'listUsageReport', 'listHostDetail', '_getFlavorListForCnt', '_getContInfo', 'setData', 'success' ));
        $stb->expects($this->any())->method('getEndpoint')->will($this->returnValue($retData));
        $stb->expects($this->any())->method('listUsageReport')->will($this->returnValue($usagesInfo));
        $stb->expects($this->any())->method('listHostDetail')->will($this->returnValue($hostDetail));
        $stb->expects($this->any())->method('_getFlavorListForCnt')->will($this->returnValue($flavorListForCnt));
        $stb->expects($this->any())->method('_getContInfo')->will($this->returnValue($getContInfo));
        $stb->expects($this->any())->method('setData')->will($this->returnValue($setData));
        $stb->expects($this->any())->method('success')->will($this->returnArgument(0));
        $stb->_nalConf['api_type'] = 'wim'; // Wim
        $stb->_p['use_type'] = '2';
        $stb->_p['dc_id']    = 'dc01';

        try {
            $method->invoke($stb);
        }catch( Exception $e){
            $this->assertEquals($e->getMessage(),'');
        }

        $wimResult = array(
            'result' => array(
                'status' => 'error',
                'error-code' => 'NAL110001',
                'message' => 'wim error'
            ),
            'data' => array(
            )
        );

        $stb = $this->getMock('cpu_detail',array( '_execMultiApi', '_execApi' ));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnValue($execList));
        $stb->expects($this->any())->method('_execApi')->will($this->returnValue($wimResult));

        try {
            $method->invoke($stb);
        }catch( Exception $e){
            $this->assertEquals($e->getMessage(),'wim error');
        }

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'cpu_detail';
        $_GET['scenario']          = 'resource';
        $_GET['pod_id'] = 'pod0001';

        $ret = new cpu_detail();
        $method = new ReflectionMethod( $ret, 'get' );
        $method->setAccessible( true );

        // dummy data Pod
        $execList['pod_info'][0]['use_type'] = 1;

        $usagesInfo = array(
            'tenant_usages' => array(
            )
        );

        $setData = array(
            'total_count' => array(
                'quota' => '0',
                'use_cnt' => '0',
            ),
            'contract_info' => array(
            )
        );

        $wimResult = array(
            'result' => array(
                'status' => 'success'
            ),
            'data' => array(
                'wim_check_flg' => 1,
                'total_count' => array(
                    'quota' => '3',
                    'use_cnt' => '1900',
                ),
                'use_info' => array(
                    '1234' => '900',
                    '2345' => '1000',
                ),
                'flavor_list_for_cnt' => $flavorListForCnt,
            )
        );

        // case 6
        $stb = $this->getMock('cpu_detail',array( '_execMultiApi', '_execApi', 'getEndpoint', 'listUsageReport', 'listHostDetail', 'setData', '_getFlavorListForCnt', '_getContInfo', 'success' ));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnValue($execList));
        $stb->expects($this->any())->method('_execApi')->will($this->returnValue($wimResult));
        $stb->expects($this->any())->method('getEndpoint')->will($this->returnValue($retData));
        $stb->expects($this->any())->method('listUsageReport')->will($this->returnValue($usagesInfo));
        $stb->expects($this->any())->method('listHostDetail')->will($this->returnValue($hostDetail));
        $stb->expects($this->any())->method('_getFlavorListForCnt')->will($this->returnValue($flavorListForCnt));
        $stb->expects($this->any())->method('setData')->will($this->returnValue($setData));
        $stb->expects($this->any())->method('_getContInfo')->will($this->returnValue($getContInfo));
        $stb->expects($this->any())->method('success')->will($this->returnArgument(0));
        $this->assertEquals( $method->invoke($stb),'');

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'memory_detail';
        $_GET['scenario']          = 'resource';
        $_GET['pod_id'] = 'pod0001';

        $ret = new cpu_detail();
        $method = new ReflectionMethod( $ret, 'get' );
        $method->setAccessible( true );

        // dummy data Pod
        $execList['pod_info'][0]['use_type'] = 1;

        // case 7
        $stb = $this->getMock('cpu_detail',array( '_execMultiApi', '_execApi', 'getEndpoint', 'success' ));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnValue($execList));
        $stb->expects($this->any())->method('_execApi')->will($this->returnValue($wimResultNoData));
        $stb->expects($this->any())->method('getEndpoint')->will($this->returnValue(array()));
        $stb->expects($this->any())->method('success')->will($this->returnArgument(0));
        $this->assertEquals( $method->invoke($stb),'');

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'storage_detail';
        $_GET['scenario']          = 'resource';
        $_GET['pod_id'] = 'pod0001';

        $ret = new cpu_detail();
        $method = new ReflectionMethod( $ret, 'get' );
        $method->setAccessible( true );

        // dummy data Pod
        $retPodData[0]['use_type'] = '1';

        // case 8
        $stb = $this->getMock('cpu_detail',array( '_execMultiApi', '_execApi', 'getEndpoint', 'success' ));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnValue($execList));
        $stb->expects($this->any())->method('_execApi')->will($this->returnValue($wimResultNoData));
        $stb->expects($this->any())->method('getEndpoint')->will($this->returnValue(array()));
        $stb->expects($this->any())->method('success')->will($this->returnArgument(0));
        $this->assertEquals( $method->invoke($stb),'');

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'memory_detail';
        $_GET['scenario']          = 'resource';
        $_GET['pod_id'] = 'pod0001';

        $ret = new cpu_detail();
        $method = new ReflectionMethod( $ret, 'get' );
        $method->setAccessible( true );

        // case 9
        $stb = $this->getMock('cpu_detail',array( '_execMultiApi', '_execApi', 'getEndpoint', 'listUsageReport', 'listHostDetail', 'setData', '_getFlavorListForCnt', '_getContInfo', 'success' ));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnValue($execList));
        $stb->expects($this->any())->method('_execApi')->will($this->returnValue($wimResult));
        $stb->expects($this->any())->method('getEndpoint')->will($this->returnValue($retData));
        $stb->expects($this->any())->method('listUsageReport')->will($this->returnValue($usagesInfo));
        $stb->expects($this->any())->method('listHostDetail')->will($this->returnValue($hostDetail));
        $stb->expects($this->any())->method('_getFlavorListForCnt')->will($this->returnValue($flavorListForCnt));
        $stb->expects($this->any())->method('setData')->will($this->returnValue($setData));
        $stb->expects($this->any())->method('_getContInfo')->will($this->returnValue($getContInfo));
        $stb->expects($this->any())->method('success')->will($this->returnArgument(0));
        $this->assertEquals( $method->invoke($stb),'');

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'storage_detail';
        $_GET['scenario']          = 'resource';
        $_GET['pod_id'] = 'pod0001';

        $ret = new cpu_detail();
        $method = new ReflectionMethod( $ret, 'get' );
        $method->setAccessible( true );

        // case 10
        $stb = $this->getMock('cpu_detail',array( '_execMultiApi', '_execApi', 'getEndpoint', 'listUsageReport', 'listHostDetail', 'setData', '_getFlavorListForCnt', '_getContInfo', 'success' ));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnValue($execList));
        $stb->expects($this->any())->method('_execApi')->will($this->returnValue($wimResult));
        $stb->expects($this->any())->method('getEndpoint')->will($this->returnValue($retData));
        $stb->expects($this->any())->method('listUsageReport')->will($this->returnValue($usagesInfo));
        $stb->expects($this->any())->method('listHostDetail')->will($this->returnValue($hostDetail));
        $stb->expects($this->any())->method('_getFlavorListForCnt')->will($this->returnValue($flavorListForCnt));
        $stb->expects($this->any())->method('setData')->will($this->returnValue($setData));
        $stb->expects($this->any())->method('_getContInfo')->will($this->returnValue($getContInfo));
        $stb->expects($this->any())->method('success')->will($this->returnArgument(0));
        $this->assertEquals( $method->invoke($stb),'');

    }

    /**
     * @covers cpu_detail::_execResult
     * @todo   Implement testExecResult().
     */
    public function testExecResult()
    {
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type'] = 'resource';
        $_SERVER['REQUEST_URI'] = "/Nal/resource/";
        $ret = new cpu_detail();
        $method = new ReflectionMethod($ret, '_execResult');
        $method->setAccessible(true);

        $url = 'http://127.0.0.1/Nal/';

        // case 1
        $err = array();
        $this->assertEquals($method->invoke($ret,$err,$url),'');

        // case 2
        $err['result'] = array( 'error-code' => 'NAL100000', 'message' => '' );
        try{
            $method->invoke($ret,$err,$url);
        }catch(Exception $e){
            $this->assertEquals('',$e->getMessage());
        }

        // case 3
        $err['result'] = array( 'error-code' => 'NAL140001', 'message' => 'test' );
        try{
            $method->invoke($ret,$err,$url);
        }catch(Exception $e){
            $this->assertEquals('test',$e->getMessage());
        }
    }

    /**
     * @covers cpu_detail::_getFlavorListForCnt
     * @todo   Implement testGetFlavorListForCnt().
     */
    public function testGetFlavorListForCnt()
    {
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'cpu_detail';
        $_GET['scenario']          = 'resource';
        $_GET['type_detail']       = '3';

        $ret = new cpu_detail();
        $method = new ReflectionMethod( $ret, '_getFlavorListForCnt' );
        $method->setAccessible( true );

        $config = array(
            'os_image_and_flavor_name_list'=> array (
                '1'=> array (
                    '1'=> array (
                        'flavor_name'=>'intersecvm_sg-v4.1-M4D30E0S0C2F1.0P1',
                        'image_name'=>'intersecvm_sg-v4.1',
                    ),
                    '2'=> array (
                        'flavor_name'=>'fortigate_vm-5.2.4-M1D30E0S0C1F1.0P1',
                        'image_name'=>'fortigate_vm-5.2.4',
                    ),
                    '3'=> array (
                        'flavor_name'=>'paloalto_vm-7.0.5-M4D40E0S0C2F1.0P1',
                        'image_name'=>'paloalto_vm-7.0.5',
                    ),
                    '4'=> array (
                        'flavor_name'=>'intersecvm_sg-v4.1-M4D30E0S0C2F1.0P1',
                        'image_name'=>'intersecvm_sg-v4.1',
                    ),
                    '5'=> array (
                        'flavor_name'=>'',
                        'image_name'=>'',
                    ),
                ),
                '2'=> array (
                    '1'=> array (
                        'flavor_name'=>'intersecvm_lb-4.0-M16D50E0S0C2F1.0P1',
                        'image_name'=>'intersecvm_lb-4.0',
                      ),
                    '2'=> array (
                        'flavor_name'=>'big_ip_ve-12.0.0.0.0.606-M4D139E0S0C2F1.0P1',
                        'image_name'=>'big_ip-12.0.0.0.0.606',
                    ),
                    '3'=> array (
                        'flavor_name'=>'vthunder-4.0.1-M2D8E0S0C1F1.0P1',
                        'image_name'=>'vthunder-4.0.1',
                    ),
                ),
                '3'=> array (
                    '1'=> array (
                        'flavor_name'=>'vsrx-12.1x47_d20.7-M2D2E0S0C2F1.0P1',
                        'image_name'=>'vsrx-12.1x47_d20.7',
                    ),
                    '2'=> array (
                        'flavor_name'=>'csr1000v-03.17.01-M4D8E0S0C4F1.0P1',
                        'image_name'=>'csr1000v-03.17.01',
                    ),
                ),
            )
        );
        $confInfo[0]['config_info'] = json_encode( $config );

        $flavorCnt = array(
            'flavors' => array(
                '0' => array(
                    'name'  => 'intersecvm_sg-v4.1-M4D30E0S0C2F1.0P1',
                    'vcpus' => '1',
                    'disk'  => '2',
                    'ram'   => '3000',
                ),
                '1' => array(
                    'name'  => 'intersecvm_lb-4.0-M16D50E0S0C2F1.0P1',
                    'vcpus' => '2',
                    'disk'  => '3',
                    'ram'   => '4000',
                ),
                '2' => array(
                    'name'  => 'vthunder-4.0.1-M2D8E0S0C1F1.0P1',
                    'vcpus' => '3',
                    'disk'  => '4',
                    'ram'   => '5000',
                ),
            ),
        );

        // dummy data Endpoint
        $endpoint_info['endpoint']           = 'http://10.58.70.89:5000/v2.0';
        $endpoint_info['user_id']            = 'admin';
        $endpoint_info['user_password']      = 'admin';
        $endpoint_info['user_key']           = '0fba6fb2f1cf40d68928aafd39e981d1';
        $endpoint_info['role_id']            = '9715c36ef48c44d0ad4bca16d863cc25';
        $endpoint_info['admin_tenant_name']  = 'admin';

        $retData[0]['endpoint_info'] = json_encode( $endpoint_info );

        $result = array(
            '1'=> array(
                '1' => array( 'count' => '1' ),
                '4' => array( 'count' => '1' ),
            ),
            '2'=> array(
                '1' => array( 'count' => '2' ),
                '3' => array( 'count' => '3' ),
            ),
        );

        // case 1
        $stb = $this->getMock('cpu_detail',array( 'getConfig', 'getEndpoint', 'listFlavorsDetail'));
        $stb->expects($this->any())->method('getConfig')->will($this->returnValue( $confInfo ));
        $stb->expects($this->any())->method('getEndpoint')->will($this->returnValue($retData));
        $stb->expects($this->any())->method('listFlavorsDetail')->will($this->returnValue($flavorCnt));
        $this->assertEquals( $method->invoke($stb, 'pod0001', $retData), $result);

        // case 2
        $stb = $this->getMock('cpu_detail',array( 'getConfig', 'getEndpoint', 'listFlavorsDetail'));
        $stb->expects($this->any())->method('getConfig')->will($this->returnValue( array() ));
        $this->assertEquals( $method->invoke($stb, 'pod0001', $retData), array());

    }

    /**
     * @covers cpu_detail::setFlavorData
     * @todo   Implement testSetFlavorData().
     */
    public function testSetFlavorData()
    {
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'cpu_detail';
        $_GET['scenario']          = 'resource';
        $_GET['type_detail']       = '3';

        $ret = new cpu_detail();
        $method = new ReflectionMethod( $ret, 'setFlavorData' );
        $method->setAccessible( true );

        $config = array(
            'os_image_and_flavor_name_list'=> array (
                '1'=> array (
                    '1'=> array (
                        'flavor_name'=>'intersecvm_sg-v4.1-M4D30E0S0C2F1.0P1',
                        'image_name'=>'intersecvm_sg-v4.1',
                    ),
                    '2'=> array (
                        'flavor_name'=>'fortigate_vm-5.2.4-M1D30E0S0C1F1.0P1',
                        'image_name'=>'fortigate_vm-5.2.4',
                    ),
                    '3'=> array (
                        'flavor_name'=>'paloalto_vm-7.0.5-M4D40E0S0C2F1.0P1',
                        'image_name'=>'paloalto_vm-7.0.5',
                    ),
                    '4'=> array (
                        'flavor_name'=>'intersecvm_sg-v4.1-M4D30E0S0C2F1.0P1',
                        'image_name'=>'intersecvm_sg-v4.1',
                    ),
                    '5'=> array (
                        'flavor_name'=>'',
                        'image_name'=>'',
                    ),
                ),
                '2'=> array (
                    '1'=> array (
                        'flavor_name'=>'intersecvm_lb-4.0-M16D50E0S0C2F1.0P1',
                        'image_name'=>'intersecvm_lb-4.0',
                      ),
                    '2'=> array (
                        'flavor_name'=>'big_ip_ve-12.0.0.0.0.606-M4D139E0S0C2F1.0P1',
                        'image_name'=>'big_ip-12.0.0.0.0.606',
                    ),
                    '3'=> array (
                        'flavor_name'=>'vthunder-4.0.1-M2D8E0S0C1F1.0P1',
                        'image_name'=>'vthunder-4.0.1',
                    ),
                ),
                '3'=> array (
                    '1'=> array (
                        'flavor_name'=>'vsrx-12.1x47_d20.7-M2D2E0S0C2F1.0P1',
                        'image_name'=>'vsrx-12.1x47_d20.7',
                    ),
                    '2'=> array (
                        'flavor_name'=>'csr1000v-03.17.01-M4D8E0S0C4F1.0P1',
                        'image_name'=>'csr1000v-03.17.01',
                    ),
                ),
            )
        );

        $flavorCnt = array(
            'flavors' => array(
                '0' => array(
                    'name'  => 'intersecvm_sg-v4.1-M4D30E0S0C2F1.0P1',
                    'vcpus' => '1',
                    'disk'  => '2000',
                    'ram'   => '500',
                ),
                '1' => array(
                    'name'  => 'intersecvm_lb-4.0-M16D50E0S0C2F1.0P1',
                    'vcpus' => '2',
                    'disk'  => '3000',
                    'ram'   => '600',
                ),
                '2' => array(
                    'name'  => 'vthunder-4.0.1-M2D8E0S0C1F1.0P1',
                    'vcpus' => '3',
                    'disk'  => '4000',
                    'ram'   => '700',
                ),
            ),
        );

        $result = array();
        $result[1][1]['count'] = '1';
        $result[1][4]['count'] = '1';
        $result[2][1]['count'] = '2';
        $result[2][3]['count'] = '3';

        // case 1
        $this->assertEquals( $method->invoke($ret, $config['os_image_and_flavor_name_list'], $flavorCnt ), $result);


        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'storage_detail';
        $_GET['scenario']          = 'resource';
        $_GET['type_detail']       = '3';

        $ret = new cpu_detail();
        $method = new ReflectionMethod( $ret, 'setFlavorData' );
        $method->setAccessible( true );

        $result = array();
        $result[1][1]['count'] = '2000';
        $result[1][4]['count'] = '2000';
        $result[2][1]['count'] = '3000';
        $result[2][3]['count'] = '4000';

        // case 2
        $this->assertEquals( $method->invoke($ret, $config['os_image_and_flavor_name_list'], $flavorCnt ), $result);

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'memory_detail';
        $_GET['scenario']          = 'resource';
        $_GET['type_detail']       = '3';

        $ret = new cpu_detail();
        $method = new ReflectionMethod( $ret, 'setFlavorData' );
        $method->setAccessible( true );

        $result = array();
        $result[1][1]['count'] = '500';
        $result[1][4]['count'] = '500';
        $result[2][1]['count'] = '600';
        $result[2][3]['count'] = '700';

        // case 3
        $this->assertEquals( $method->invoke($ret, $config['os_image_and_flavor_name_list'], $flavorCnt ), $result);

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'storage_detail';
        $_GET['scenario']          = 'resource';
        $_GET['type_detail']       = '2';

        $flavorCnt = array(
            'flavors' => array(
                '0' => array(
                    'name'  => 'csr1000v-03.17.01-M4D8E0S0C4F1.0P1',
                    'vcpus' => '3',
                    'disk'  => '300',
                    'ram'   => '500',
                ),
                '1' => array(
                    'name'  => 'intersecvm_lb-4.0-M16D50E0S0C2F1.0P1',
                    'vcpus' => '2',
                    'disk'  => '3000',
                    'ram'   => '600',
                ),
                '2' => array(
                    'name'  => 'vthunder-4.0.1-M2D8E0S0C1F1.0P1',
                    'vcpus' => '3',
                    'disk'  => '4000',
                    'ram'   => '700',
                ),
            ),
        );

        $result = array();
        $result[3][2]['count'] = '500';

        // case 4
        $ret->_nalConf['api_type'] = 'wim';
        $this->assertEquals( $method->invoke($ret, $config['os_image_and_flavor_name_list'], $flavorCnt ), $result);

    }

    /**
     * @covers cpu_detail::setData
     * @todo   Implement testSetData().
     */
    public function testSetData()
    {
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'cpu_detail';
        $_GET['scenario']          = 'resource';
        $_GET['type_detail']       = '3';

        $tenantList = array(
            '1234' => array(
                          'tenant_name'    => 'tenant1',
                          'ID'             => '1',
                          'IaaS_tenant_id' => '1234',
                      ),
            '2345' => array(
                          'tenant_name'    => 'tenant2',
                          'ID'             => '3',
                          'IaaS_tenant_id' => '2345',
                      ),
        );

        $usagesInfo = array(
            'tenant_usages' => array(
                '0' => array(
                    'tenant_id' => '1234',
                    'server_usages' => array(
                        '0' => array(
                            'instance_id' => '1234',
                            'vcpus' => 1,
                            'memory_mb' => 3000,
                            'local_gb' => 500,
                        ),
                        '1' => array(
                            'instance_id' => '2345',
                            'vcpus' => 1,
                            'memory_mb' => 2000,
                            'local_gb' => 300,
                        )
                    )
                ),
                '1' => array(
                    'tenant_id' => '2345',
                    'server_usages' => array(
                        '0' => array(
                            'instance_id' => '3456',
                            'vcpus' => 1,
                            'memory_mb' => 2000,
                            'local_gb' => 300,
                        ),
                        '1' => array(
                            'instance_id' => '4567',
                            'vcpus' => 2,
                            'memory_mb' => 1500,
                            'local_gb' => 200,
                        )
                    )
                )
            )
        );

        $hostDetail = array(
            '0' => array(
                'cpu' => 5,
                'disk_gb' => 2000,
                'memory_mb' => 8200,
            ),
            '1' => array(
                'cpu' => 10,
                'disk_gb' => 2000,
                'memory_mb' => 8200,
            )
        );

        $ret = new cpu_detail();
        $reflection_class = new ReflectionClass( $ret );
        $property = $reflection_class->getProperty('_quotaInfo');
        $property->setAccessible( true );

        $property->setValue($ret, $hostDetail );

        $property = $reflection_class->getProperty('_usagesInfo');
        $property->setAccessible( true );

        $property->setValue($ret, $usagesInfo );

        $method = $reflection_class->getMethod('setData');
        $method->setAccessible(true);

        $setData = array(
            'total_info' => array(
                'quota' => '15',
            ),
            'use_info' => array(
                '1234' => 1,
                '2345' => 1,
                '3456' => 1,
                '4567' => 2,
            )
        );

        // case 1
        $this->assertEquals( $method->invoke($ret, $tenantList),$setData);

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'memory_detail';
        $_GET['scenario']          = 'resource';
        $_GET['type_detail']       = '3';

        $ret = new cpu_detail();
        $reflection_class = new ReflectionClass( $ret );
        $property = $reflection_class->getProperty('_quotaInfo');
        $property->setAccessible( true );

        $property->setValue($ret, $hostDetail );

        $property = $reflection_class->getProperty('_usagesInfo');
        $property->setAccessible( true );

        $property->setValue($ret, $usagesInfo );

        $method = $reflection_class->getMethod('setData');
        $method->setAccessible(true);

        $setData = array(
            'total_info' => array(
                'quota' => '16400MB',
            ),
            'use_info' => array(
                '1234' => 3000,
                '2345' => 2000,
                '3456' => 2000,
                '4567' => 1500,
            )
        );

        // case 2
        $this->assertEquals( $method->invoke($ret, $tenantList),$setData);

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'storage_detail';
        $_GET['scenario']          = 'resource';
        $_GET['type_detail']       = '3';

        $ret = new cpu_detail();
        $reflection_class = new ReflectionClass( $ret );
        $property = $reflection_class->getProperty('_quotaInfo');
        $property->setAccessible( true );

        $property->setValue($ret, $hostDetail );

        $property = $reflection_class->getProperty('_usagesInfo');
        $property->setAccessible( true );

        $property->setValue($ret, $usagesInfo );

        $method = $reflection_class->getMethod('setData');
        $method->setAccessible(true);

        $setData = array(
            'total_info' => array(
                'quota' => '4000GB',
            ),
            'use_info' => array(
                '1234' => 500,
                '2345' => 300,
                '3456' => 300,
                '4567' => 200,
            )
        );

        // case 3
        $this->assertEquals( $method->invoke($ret, $tenantList),$setData);

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'cpu_detail';
        $_GET['scenario']          = 'resource';
        $_GET['type_detail']       = '3';

        $usagesInfo = array(
            'tenant_usages' => array(
            )
        );

        $ret = new cpu_detail();
        $reflection_class = new ReflectionClass( $ret );
        $property = $reflection_class->getProperty('_quotaInfo');
        $property->setAccessible( true );

        $property->setValue($ret, $hostDetail );

        $property = $reflection_class->getProperty('_usagesInfo');
        $property->setAccessible( true );

        $property->setValue($ret, $usagesInfo );

        $method = $reflection_class->getMethod('setData');
        $method->setAccessible(true);

        $setData = array(
            'total_info' => array(
                'quota' => '15',
            ),
            'use_info' => array(
            )
        );

        // case 4
        $this->assertEquals( $method->invoke($ret, $tenantList),$setData);

    }

    /**
     * @covers cpu_detail::_getContInfo
     * @todo   Implement testGetContInfo().
     */
    public function testGetContInfo()
    {
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'cpu_detail';
        $_GET['scenario']          = 'resource';
        $_GET['pod_id']            = '3';

        $ret = new cpu_detail();
        $method = new ReflectionMethod( $ret, '_getContInfo' );
        $method->setAccessible( true );

        $execList = array(
            'pod_info' => array(
                '0' => array(
                    'pod_id'   => 'pod0001',
                    'use_type' => '1',
                ),
            ),
            'apl_info' => array(
                '0' => array(
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID'             => '1',
                    'node_id'        => '1234',
                ),
                '1' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '2',
                    'node_id'        => '2345',
                ),
                '2' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '3',
                    'node_id'        => '3456',
                ),
                '3' => array(
                    'tenant_name'    => 'tenant3',
                    'IaaS_tenant_id' => '3456',
                    'ID'             => '4',
                    'node_id'        => '5555',
                )
            ),
            'tenant_contract_info' => array(
                '0' => array(
                    'apl_type'       => 1,
                    'type'           => 1,
                    'device_type'    => 1,
                    'contract'       => '2',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 2,
                ),
                '1' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 1,
                    'contract'    => '4',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 3,
                ),
                '2' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 3,
                    'contract'    => '6',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 4,
                ),
                '3' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 3,
                    'contract'    => '6',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID' => 5,
                ),
                '4' => array(
                    'apl_type'    => 1,
                    'type'        => 3,
                    'device_type' => 2,
                    'contract'    => '1',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID' => 6,
                ),
                '5' => array(
                    'apl_type'    => 2,
                    'type'        => 1,
                    'device_type' => 2,
                    'contract'    => '1',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID' => 7,
                ),
            )
        );

        $flavorListForCnt[1][1]['count'] = '10';
        $flavorListForCnt[1][2]['count'] = '10';
        $flavorListForCnt[1][3]['count'] = '10';
        $flavorListForCnt[1][4]['count'] = '10';
        $flavorListForCnt[1][5]['count'] = '10';
        $flavorListForCnt[2][1]['count'] = '20';
        $flavorListForCnt[2][2]['count'] = '20';
        $flavorListForCnt[2][3]['count'] = '20';
        $flavorListForCnt[2][4]['count'] = '20';

        $flavorListForCntWim[3][2]['count'] = '30';

        $nalData = array(
            'total_info' => array(
                'quota' => '3',
                'use_cnt' => '1900',
            ),
            'use_info' => array(
                '1234' => '900',
                '2345' => '1000',
            ),
            'flavor_list_for_cnt' => $flavorListForCnt,
        );

        $wimData = array(
            'wim_check_flg' => 1,
            'flavor_list_for_cnt' => $flavorListForCntWim,
        );

        $result = array(
            'total_info' => array(
                'quota' => '3',
                'use_cnt' => '1900',
            ),
            'contract_info' => array(
                '0' => array(
                    'ID'             => '0',
                    'use_cnt'        => '900',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'contract_cnt'   => '220',
                ),
                '1' => array(
                    'ID'             => '1',
                    'use_cnt'        => '1000',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'contract_cnt'   => '120',
                ),
            )
        );

        // case 1
        $this->assertEquals( $method->invoke($ret, $nalData, $wimData, $execList), $result);

        $execList = array(
            'pod_info' => array(
                '0' => array(
                    'pod_id'   => 'pod0001',
                    'use_type' => '1',
                ),
            ),
            'apl_info' => array(
                '0' => array(
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID'             => '1',
                    'node_id'        => '1234',
                ),
                '1' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '2',
                    'node_id'        => '2345',
                ),
                '2' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '3',
                    'node_id'        => '3456',
                ),
                '3' => array(
                    'tenant_name'    => 'tenant3',
                    'IaaS_tenant_id' => '3456',
                    'ID'             => '4',
                    'node_id'        => '5555',
                )
            ),
            'tenant_contract_info' => array(
                '0' => array(
                    'apl_type'       => 1,
                    'type'           => 1,
                    'device_type'    => 1,
                    'contract'       => '2',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 2,
                ),
                '1' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 1,
                    'contract'    => '4',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 3,
                ),
                '2' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 3,
                    'contract'    => '6',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 4,
                ),
                '3' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 3,
                    'contract'    => '6',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID' => 5,
                ),
                '4' => array(
                    'apl_type'    => 1,
                    'type'        => 3,
                    'device_type' => 2,
                    'contract'    => '1',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID' => 6,
                ),
                '5' => array(
                    'apl_type'    => 1,
                    'type'        => 1,
                    'device_type' => 1,
                    'contract'    => '10',
                    'tenant_name'    => 'tenant4',
                    'IaaS_tenant_id' => '4567',
                    'ID' => 6,
                ),
            )
        );

        $nalData = array(
            'total_info' => array(
                'quota' => '3',
            ),
            'use_info' => array(
                '1234' => '900',
                '2345' => '1000',
                '5555' => '1000',
            ),
            'flavor_list_for_cnt' => $flavorListForCnt,
        );

        $wimData = array(
            'wim_check_flg' => 1,
            'flavor_list_for_cnt' => $flavorListForCntWim,
        );

        $result = array(
            'total_info' => array(
                'quota' => '3',
                'use_cnt' => '2900',
            ),
            'contract_info' => array(
                '0' => array(
                    'ID'             => '0',
                    'use_cnt'        => '900',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'contract_cnt'   => '220',
                ),
                '1' => array(
                    'ID'             => '1',
                    'use_cnt'        => '1000',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'contract_cnt'   => '120',
                ),
                '2' => array(
                    'ID'             => '2',
                    'use_cnt'        => '1000',
                    'tenant_name'    => 'tenant3',
                    'IaaS_tenant_id' => '3456',
                    'contract_cnt'   => '0',
                ),
                '3' => array(
                    'ID'             => '3',
                    'use_cnt'        => '0',
                    'contract_cnt'   => '100',
                    'tenant_name'    => 'tenant4',
                    'IaaS_tenant_id' => '4567',
                ),
            )
        );

        // case 2
        $this->assertEquals( $method->invoke($ret, $nalData, $wimData, $execList), $result);

        $nalData = array(
            'total_info' => array(
                'quota' => '3',
            ),
            'use_info' => array(
                '1234' => '900',
                '2345' => '1000',
                '3456' => '1000',
                '5555' => '1000',
            ),
            'flavor_list_for_cnt' => $flavorListForCnt,
        );

        $result = array(
            'total_info' => array(
                'quota' => '3',
                'use_cnt' => '3900',
            ),
            'contract_info' => array(
                '0' => array(
                    'ID'             => '0',
                    'use_cnt'        => '900',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'contract_cnt'   => '220',
                ),
                '1' => array(
                    'ID'             => '1',
                    'use_cnt'        => '2000',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'contract_cnt'   => '120',
                ),
                '2' => array(
                    'ID'             => '2',
                    'use_cnt'        => '1000',
                    'tenant_name'    => 'tenant3',
                    'IaaS_tenant_id' => '3456',
                    'contract_cnt'   => '0',
                ),
                '3' => array(
                    'ID'             => '3',
                    'use_cnt'        => '0',
                    'contract_cnt'   => '100',
                    'tenant_name'    => 'tenant4',
                    'IaaS_tenant_id' => '4567',
                ),
            )
        );

        // case 3
        $this->assertEquals( $method->invoke($ret, $nalData, $wimData, $execList), $result);

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'memory_detail';
        $_GET['scenario']          = 'resource';
        $_GET['pod_id']            = '3';

        $ret = new cpu_detail();
        $method = new ReflectionMethod( $ret, '_getContInfo' );
        $method->setAccessible( true );

        $execList = array(
            'pod_info' => array(
                '0' => array(
                    'pod_id'   => 'pod0001',
                    'use_type' => '3',
                ),
            ),
            'apl_info' => array(
                '0' => array(
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID'             => '1',
                    'node_id'        => '1234',
                ),
                '1' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '2',
                    'node_id'        => '2345',
                ),
                '2' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '3',
                    'node_id'        => '3456',
                ),
                '3' => array(
                    'tenant_name'    => 'tenant3',
                    'IaaS_tenant_id' => '3456',
                    'ID'             => '4',
                    'node_id'        => '5555',
                )
            ),
            'tenant_contract_info' => array(
                '0' => array(
                    'apl_type'       => 1,
                    'type'           => 1,
                    'device_type'    => 1,
                    'contract'       => '2',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 2,
                ),
                '1' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 1,
                    'contract'    => '4',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 3,
                ),
                '2' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 3,
                    'contract'    => '6',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 4,
                ),
                '3' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 3,
                    'contract'    => '6',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID' => 5,
                ),
                '4' => array(
                    'apl_type'    => 1,
                    'type'        => 3,
                    'device_type' => 2,
                    'contract'    => '1',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID' => 6,
                ),
                '5' => array(
                    'apl_type'    => 1,
                    'type'        => 3,
                    'device_type' => 2,
                    'contract'    => '10',
                    'tenant_name'    => 'tenant4',
                    'IaaS_tenant_id' => '4567',
                    'ID' => 6,
                ),
            )
        );

        $flavorListForCnt[1][1]['count'] = '100';
        $flavorListForCnt[1][1]['count'] = '100';
        $flavorListForCnt[1][1]['count'] = '100';
        $flavorListForCnt[1][2]['count'] = '100';
        $flavorListForCnt[1][3]['count'] = '100';
        $flavorListForCnt[1][4]['count'] = '100';
        $flavorListForCnt[1][5]['count'] = '100';
        $flavorListForCnt[2][1]['count'] = '200';
        $flavorListForCnt[2][2]['count'] = '200';
        $flavorListForCnt[2][3]['count'] = '200';
        $flavorListForCnt[2][4]['count'] = '200';

        $flavorListForCntWim[3][2]['count'] = '300';

        $nalData = array(
            'total_info' => array(
                'quota' => '3',
            ),
            'use_info' => array(
                '1234' => '900',
                '2345' => '1000',
                '5555' => '1000',
                '8888' => '1000',
            ),
            'flavor_list_for_cnt' => $flavorListForCnt,
        );

        $wimData = array(
            'wim_check_flg' => 1,
            'flavor_list_for_cnt' => $flavorListForCntWim,
        );

        $result = array(
            'total_info' => array(
                'quota' => '3',
                'use_cnt' => '2900MB',
            ),
            'contract_info' => array(
                '0' => array(
                    'ID'             => '0',
                    'use_cnt'        => '900MB',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'contract_cnt'   => '2200MB',
                ),
                '1' => array(
                    'ID'             => '1',
                    'use_cnt'        => '1000MB',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'contract_cnt'   => '1800MB',
                ),
                '2' => array(
                    'ID'             => '2',
                    'use_cnt'        => '1000MB',
                    'tenant_name'    => 'tenant3',
                    'IaaS_tenant_id' => '3456',
                    'contract_cnt'   => '0MB',
                ),
                '3' => array(
                    'ID'             => '3',
                    'use_cnt'        => '0MB',
                    'contract_cnt'   => '600MB',
                    'tenant_name'    => 'tenant4',
                    'IaaS_tenant_id' => '4567',
                ),
            )
        );

        // case 4
        $this->assertEquals( $method->invoke($ret, $nalData, $wimData, $execList), $result);


        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'storage_detail';
        $_GET['scenario']          = 'resource';
        $_GET['pod_id']            = '3';

        $ret = new cpu_detail();
        $method = new ReflectionMethod( $ret, '_getContInfo' );
        $method->setAccessible( true );

        $execList['pod_info'][0]['use_type'] = '2';

        $flavorListForCnt[1][1]['count'] = '1000';
        $flavorListForCnt[1][1]['count'] = '1000';
        $flavorListForCnt[1][1]['count'] = '1000';
        $flavorListForCnt[1][2]['count'] = '1000';
        $flavorListForCnt[1][3]['count'] = '1000';
        $flavorListForCnt[1][4]['count'] = '1000';
        $flavorListForCnt[1][5]['count'] = '1000';
        $flavorListForCnt[2][1]['count'] = '2000';
        $flavorListForCnt[2][2]['count'] = '2000';
        $flavorListForCnt[2][3]['count'] = '2000';
        $flavorListForCnt[2][4]['count'] = '2000';

        $flavorListForCntWim[3][2]['count'] = '3000';

        $nalData = array(
            'flavor_list_for_cnt' => $flavorListForCnt,
        );

        $wimData = array(
            'wim_check_flg' => 1,
            'total_info' => array(
                'quota' => '5000GB',
            ),
            'use_info' => array(
                '1234' => '900',
                '2345' => '1000',
            ),
            'flavor_list_for_cnt' => $flavorListForCntWim,
        );

        $result = array(
            'total_info' => array(
                'quota' => '5000GB',
                'use_cnt' => '1900GB',
            ),
            'contract_info' => array(
                '0' => array(
                    'ID'             => '0',
                    'use_cnt'        => '900GB',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'contract_cnt'   => '0GB',
                ),
                '1' => array(
                    'ID'             => '1',
                    'use_cnt'        => '1000GB',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'contract_cnt'   => '6000GB',
                ),
                '2' => array(
                    'ID'             => '2',
                    'use_cnt'        => '0GB',
                    'contract_cnt'   => '6000GB',
                    'tenant_name'    => 'tenant4',
                    'IaaS_tenant_id' => '4567',
                ),
            )
        );

        // case 5
        $this->assertEquals( $method->invoke($ret, $nalData, $wimData, $execList), $result);

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'storage_detail';
        $_GET['scenario']          = 'resource';
        $_GET['pod_id']            = '3';

        $ret = new cpu_detail();
        $method = new ReflectionMethod( $ret, '_getContInfo' );
        $method->setAccessible( true );

        $execList = array(
            'pod_info' => array(
                '0' => array(
                    'pod_id'   => 'pod0001',
                    'use_type' => '3',
                ),
            ),
            'apl_info' => array(),
            'tenant_contract_info' => array(
                '0' => array(
                    'apl_type'       => 1,
                    'type'           => 1,
                    'device_type'    => 1,
                    'contract'       => '2',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 2,
                ),
                '1' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 1,
                    'contract'    => '4',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 3,
                ),
                '2' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 3,
                    'contract'    => '6',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID' => 4,
                ),
                '3' => array(
                    'apl_type'    => 1,
                    'type'        => 2,
                    'device_type' => 3,
                    'contract'    => '6',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID' => 5,
                ),
                '4' => array(
                    'apl_type'    => 1,
                    'type'        => 3,
                    'device_type' => 2,
                    'contract'    => '1',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID' => 6,
                ),
                '5' => array(
                    'apl_type'    => 1,
                    'type'        => 3,
                    'device_type' => 2,
                    'contract'    => '10',
                    'tenant_name'    => 'tenant4',
                    'IaaS_tenant_id' => '4567',
                    'ID' => 6,
                ),
            )
        );

        $flavorListForCnt[1][1]['count'] = '1000';
        $flavorListForCnt[1][1]['count'] = '1000';
        $flavorListForCnt[1][1]['count'] = '1000';
        $flavorListForCnt[1][2]['count'] = '1000';
        $flavorListForCnt[1][3]['count'] = '1000';
        $flavorListForCnt[1][4]['count'] = '1000';
        $flavorListForCnt[1][5]['count'] = '1000';
        $flavorListForCnt[2][1]['count'] = '2000';
        $flavorListForCnt[2][2]['count'] = '2000';
        $flavorListForCnt[2][3]['count'] = '2000';
        $flavorListForCnt[2][4]['count'] = '2000';

        $flavorListForCntWim[3][2]['count'] = '3000';

        $nalData = array(
            'total_info' => array(
                'quota' => '5000GB',
            ),
            'use_info' => array(
                '1234' => '900',
                '2345' => '1000',
            ),
            'flavor_list_for_cnt' => $flavorListForCnt,
        );

        $wimData = array(
            'wim_check_flg' => 1,
            'flavor_list_for_cnt' => $flavorListForCntWim,
        );

        $result = array(
            'total_info' => array(
                'quota' => '5000GB',
                'use_cnt' => '0GB',
            ),
            'contract_info' => array(
                '0' => array(
                    'ID'             => '0',
                    'use_cnt'        => '0GB',
                    'contract_cnt'   => '22000GB',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                ),
                '1' => array(
                    'ID'             => '1',
                    'use_cnt'        => '0GB',
                    'contract_cnt'   => '18000GB',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                ),
                '2' => array(
                    'ID'             => '2',
                    'use_cnt'        => '0GB',
                    'contract_cnt'   => '6000GB',
                    'tenant_name'    => 'tenant4',
                    'IaaS_tenant_id' => '4567',
                ),
            )
        );

        // case 6
        $this->assertEquals( $method->invoke($ret, $nalData, $wimData, $execList), $result);

        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type']     = 'storage_detail';
        $_GET['scenario']          = 'resource';
        $_GET['pod_id']            = '3';

        $ret = new cpu_detail();
        $method = new ReflectionMethod( $ret, '_getContInfo' );
        $method->setAccessible( true );

        $execList = array(
            'pod_info' => array(
                '0' => array(
                    'pod_id'   => 'pod0001',
                    'use_type' => '3',
                ),
            ),
            'apl_info' => array(
                '0' => array(
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                    'ID'             => '1',
                    'node_id'        => '1234',
                ),
                '1' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '2',
                    'node_id'        => '2345',
                ),
                '2' => array(
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                    'ID'             => '3',
                    'node_id'        => '3456',
                ),
                '3' => array(
                    'tenant_name'    => 'tenant3',
                    'IaaS_tenant_id' => '3456',
                    'ID'             => '4',
                    'node_id'        => '5555',
                )
            ),
            'tenant_contract_info' => array()
        );

        $flavorListForCnt[1][1]['count'] = '1000';
        $flavorListForCnt[1][1]['count'] = '1000';
        $flavorListForCnt[1][1]['count'] = '1000';
        $flavorListForCnt[1][2]['count'] = '1000';
        $flavorListForCnt[1][3]['count'] = '1000';
        $flavorListForCnt[1][4]['count'] = '1000';
        $flavorListForCnt[1][5]['count'] = '1000';
        $flavorListForCnt[2][1]['count'] = '2000';
        $flavorListForCnt[2][2]['count'] = '2000';
        $flavorListForCnt[2][3]['count'] = '2000';
        $flavorListForCnt[2][4]['count'] = '2000';

        $flavorListForCntWim[3][2]['count'] = '3000';

        $nalData = array(
            'total_info' => array(
                'quota' => '5000GB',
            ),
            'use_info' => array(
                '1234' => '900',
                '2345' => '1000',
            ),
            'flavor_list_for_cnt' => $flavorListForCnt,
        );

        $wimData = array(
            'wim_check_flg' => 1,
            'flavor_list_for_cnt' => $flavorListForCntWim,
        );

        $result = array(
            'total_info' => array(
                'quota' => '5000GB',
                'use_cnt' => '1900GB',
            ),
            'contract_info' => array(
                '0' => array(
                    'ID'             => '0',
                    'use_cnt'        => '900GB',
                    'contract_cnt'   => '0GB',
                    'tenant_name'    => 'tenant1',
                    'IaaS_tenant_id' => '1234',
                ),
                '1' => array(
                    'ID'             => '1',
                    'use_cnt'        => '1000GB',
                    'contract_cnt'   => '0GB',
                    'tenant_name'    => 'tenant2',
                    'IaaS_tenant_id' => '2345',
                ),
            )
        );

        // case 7
        $this->assertEquals( $method->invoke($ret, $nalData, $wimData, $execList), $result);

    }

}
