<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-02 at 10:29:36.
 */

require_once dirname(__FILE__) . '/../Nal/api/app/license.php';

class licenseTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var license
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        if( !defined('PHPUNIT_RUN')) {
            define( 'PHPUNIT_RUN', 1 );
        }
        $this->homeDir = realpath( dirname(__FILE__) ) ;
        if( !defined('HOME_DIR')) {
            define( 'HOME_DIR', $this->homeDir );
        }
        if( !defined('API_DIR')) {
            define( 'API_DIR' , HOME_DIR . '' );
        }
        if( !defined('APP_DIR')) {
            define( 'APP_DIR' , API_DIR . '/Stub' );
        }
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers license::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_SERVER['REQUEST_URI'] = '/Nal/resource/?function_type=license&type=1&device_type=1';
        $_GET['function_type']    = 'license';
        $_GET['scenario']         = 'resource';
        $_GET['type']             = '1';
        $_GET['device_type']      = '1';

        $ret = new license();
        $method = new ReflectionMethod( $ret, 'get' );
        $method->setAccessible( true );

        $wimResult = array(
          'result' => array(
            'status' => 'success'
          ),
          'data' => array(
            'test' => '1'
          )
        );

        //case 1
        $stb = $this->getMock('license',array('_execMultiApi', '_execApi', '_getContInfo', 'success' ));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnArgument(0));
        $stb->expects($this->any())->method('_execApi')->will($this->returnValue($wimResult));
        $stb->expects($this->any())->method('_getContInfo')->will($this->returnValue($wimResult));
        $stb->expects($this->any())->method('success')->will($this->returnValue($wimResult));
        $this->assertEquals( $method->invoke($stb),'');

        $_GET['type']             = '1';
        $_GET['device_type']      = '3';
        $_GET['type_detail']      = '2';

        $ret = new license();
        $method = new ReflectionMethod( $ret, 'get' );
        $method->setAccessible( true );

        $wimResult = array(
            'result' => array(
                'status' => 'success'
            ),
            'data' => array(
                'test' => '1'
            )
        );

        //case 2
        $stb = $this->getMock('license',array('_execMultiApi', '_execApi', '_getContInfo', 'success' ));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnArgument(0));
        $stb->expects($this->any())->method('_execApi')->will($this->returnValue($wimResult));
        $stb->expects($this->any())->method('_getContInfo')->will($this->returnValue($wimResult));
        $stb->expects($this->any())->method('success')->will($this->returnValue($wimResult));
        $this->assertEquals( $method->invoke($stb),'');

        $ret = new license();
        $method = new ReflectionMethod( $ret, 'get' );
        $method->setAccessible( true );

        //case 3
        $stb = $this->getMock('license',array('_execMultiApi', 'success'));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnArgument(0));
        $stb->expects($this->any())->method('success')->will($this->returnValue($wimResult));
        $stb->_nalConf['api_type'] = 'wim'; // Wim
        $this->assertEquals( $method->invoke($stb),'');

    }

    /**
     * @covers license::_getContInfo
     * @todo   Implement testgetContInfo().
     */
    public function testgetContInfo(){
        // case 1
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_SERVER['REQUEST_URI'] = '/Nal/resource/?function_type=license&type=1&device_type=1';
        $_GET['function_type']    = 'license';
        $_GET['scenario']         = 'resource';
        $_GET['typoe']             = '1';
        $_GET['device_type']      = '1';

        $ret = new license();
        $method = new ReflectionMethod( $ret, '_getContInfo' );
        $method->setAccessible( true );

        $execList['tenant_info'] = array(
            '0' => array(
                'IaaS_tenant_id' => "1234",
                'tenant_name'    => "tenant_name",
                'ID'             => "4",
            )
        );

        $result = array(
          'total_info' => array(
            'quota' => '5',
            'contract_cnt' => '14',
            'use_cnt' => '14',
            'unavailable_cnt' => '2',
          ),
          'contract_info' => array(
            '0' => array(
              'contract_cnt'   => '3',
              'use_cnt'        => '3',
              'IaaS_tenant_id' => '1234',
              'tenant_name'    => 'tenant_name',
              'ID'             => '4',
            )
          )
        );

        //case 1
        $stb = $this->getMock('license',array('_getQuotaLisence', '_getContractCntLicense', '_getUseCntLicense', '_getUnavailableCntLicense', 'success'));
        $stb->expects($this->any())->method('_getQuotaLisence')->will($this->returnValue(5));
        $stb->expects($this->any())->method('_getContractCntLicense')->will($this->returnValue( array( '14', array( 'tenant_name' => array('contract_cnt' => '3','tenant_name' => 'tenant_name', 'IaaS_tenant_id' => '1234', 'ID' => '4') ) ) ));
        $stb->expects($this->any())->method('_getUseCntLicense')->will($this->returnValue( array( '14', array( 'tenant_name' => array('use_cnt' => '3') ) ) ));
        $stb->expects($this->any())->method('_getUnavailableCntLicense')->will($this->returnValue( 2 ));
        $this->assertEquals( $method->invoke($stb,$execList),$result);

        $result = array(
          'total_info' => array(
            'quota' => '5',
            'unavailable_cnt' => '2',
            'contract_cnt' => '14',
            'use_cnt' => '14',
          ),
          'contract_info' => array(
            '0' => array(
              'contract_cnt'   => '3',
              'use_cnt'        => '0',
              'IaaS_tenant_id' => '1234',
              'tenant_name'    => 'tenant_name',
              'ID'             => '4',
            )
          )
        );

        //case 1
        $stb = $this->getMock('license',array('_getQuotaLisence', '_getContractCntLicense', '_getUseCntLicense', '_getUnavailableCntLicense', 'success'));
        $stb->expects($this->any())->method('_getQuotaLisence')->will($this->returnValue(5));
        $stb->expects($this->any())->method('_getContractCntLicense')->will($this->returnValue( array( '14', array( 'tenant_name' => array('contract_cnt' => '3','tenant_name' => 'tenant_name', 'IaaS_tenant_id' => '1234', 'ID' => '4') ) ) ));
        $stb->expects($this->any())->method('_getUseCntLicense')->will($this->returnValue( array( '14', array( 'tenant_name' => array() ) ) ));
        $stb->expects($this->any())->method('_getUnavailableCntLicense')->will($this->returnValue(2));
        $this->assertEquals( $method->invoke($stb,$execList),$result);

    }

    /**
     * @covers license::_execResult
     * @todo   Implement testExecResult().
     */
    public function testExecResult()
    {
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type'] = 'resource';
        $_SERVER['REQUEST_URI'] = "/Nal/node/";
        $ret = new license();
        $method = new ReflectionMethod($ret, '_execResult');
        $method->setAccessible(true);

        $url = 'http://127.0.0.1/Nal/';

        // case 1
        $err = array();
        $this->assertEquals($method->invoke($ret,$err,$url),'');

        // case 2
        $err['result'] = array( 'error-code' => 'NAL100000', 'message' => '' );
        try{
            $method->invoke($ret,$err,$url);
        }catch(Exception $e){
            $this->assertEquals('',$e->getMessage());
        }

        // case 3
        $err['result'] = array( 'error-code' => 'NAL140001', 'message' => 'test' );
        try{
            $method->invoke($ret,$err,$url);
        }catch(Exception $e){
            $this->assertEquals('test',$e->getMessage());
        }
    }

}
