<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-02 at 13:47:50.
 */

require_once dirname(__FILE__) . '/../Nal/api/app/msa_vlan.php';

class msa_vlanTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var msa_vlan
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        if( !defined('PHPUNIT_RUN')) {
            define( 'PHPUNIT_RUN', 1 );
        }
        $this->homeDir = realpath( dirname(__FILE__) ) ;
        if( !defined('HOME_DIR')) {
            define( 'HOME_DIR', $this->homeDir );
        }
        if( !defined('API_DIR')) {
            define( 'API_DIR' , HOME_DIR . '' );
        }
        if( !defined('APP_DIR')) {
            define( 'APP_DIR' , API_DIR . '/Stub' );
        }
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers msa_vlan::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // case 1
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_SERVER['REQUEST_URI'] = '/Nal/resource/?function_type=license&type=1&device_type=1';
        $_GET['function_type']    = 'msa_vlan';
        $_GET['scenario']         = 'resource';

        $ret = new msa_vlan();
        $method = new ReflectionMethod( $ret, 'get' );
        $method->setAccessible( true );

        $result = array(
          'total_info' => array(
            'contract_cnt' => '1'
          ),
          'contract_info' => array(
            'node_id' => '1234'
          )
        );

        //case 1
        $stb = $this->getMock('msa_vlan',array('_execMultiApi', '_getContInfo', 'success'));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnArgument(0));
        $stb->expects($this->any())->method('_getContInfo')->will($this->returnValue($result));
        $stb->expects($this->any())->method('success')->will($this->returnArgument(0));
        $this->assertEquals( $method->invoke($stb), '');

        $_GET['type']             = '1';
        $_GET['device_type']      = '3';

        $ret = new msa_vlan();
        $method = new ReflectionMethod( $ret, 'get' );
        $method->setAccessible( true );

        //case 2
        $stb = $this->getMock('msa_vlan',array('_execMultiApi', '_getContInfo', 'success'));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnArgument(0));
        $stb->expects($this->any())->method('_getContInfo')->will($this->returnValue($result));
        $stb->expects($this->any())->method('success')->will($this->returnArgument(0));
        $this->assertEquals( $method->invoke($stb), '');


    }

    /**
     * @covers msa_vlan::_getContInfo
     * @todo   Implement testgetContInfo().
     */
    public function testgetContInfo(){
        // case 1
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_SERVER['REQUEST_URI'] = '/Nal/resource/?function_type=license&type=1&device_type=1';
        $_GET['function_type']    = 'msa_vlan';
        $_GET['scenario']         = 'resource';
        $_GET['type']             = '1';
        $_GET['device_type']      = '1';
        $_GET['redundant_configuration_flg']      = '1';

        $ret = new msa_vlan();
        $method = new ReflectionMethod( $ret, '_getContInfo' );
        $method->setAccessible( true );

        $aplInfo['msa_info'][0]['vlan_id'] = '806';
        $aplInfo['msa_info'][0]['tenant_name'] = 'tenant';
        $aplInfo['msa_info'][0]['IaaS_tenant_id'] = '1234';
        $aplInfo['msa_info'][0]['ID'] = 11;
        $aplInfo['msa_info'][0]['status'] = '1';

        $result = array(
          'total_info' => array(
            'quota' => '5',
            'contract_cnt' => '3',
            'use_cnt' => '4',
            'unavailable_cnt' => '5',
          ),
          'contract_info' => array(
            '0' => array(
              'vlan_id' => '806',
              'tenant_name' => 'tenant',
              'IaaS_tenant_id' => '1234',
              'ID' => 11,
              'task_status' => '1',
              'use_status' => '1',
            )
          )
        );

        //case 1
        $stb = $this->getMock('msa_vlan',array( '_getQuotaMsa', '_getContractCntMsa', '_getUseCntMsa', '_getUnavailableCntMsa'));
        $stb->expects($this->any())->method('_getQuotaMsa')->will($this->returnValue(5));
        $stb->expects($this->any())->method('_getContractCntMsa')->will($this->returnValue(3));
        $stb->expects($this->any())->method('_getUseCntMsa')->will($this->returnValue(4));
        $stb->expects($this->any())->method('_getUnavailableCntMsa')->will($this->returnValue(5));
        $this->assertEquals( $method->invoke($stb, $aplInfo),$result);

        $ret = new msa_vlan();
        $method = new ReflectionMethod( $ret, '_getContInfo' );
        $method->setAccessible( true );

        $aplInfo['msa_info'][0]['vlan_id'] = '806';
        $aplInfo['msa_info'][0]['tenant_name'] = '';
        $aplInfo['msa_info'][0]['IaaS_tenant_id'] = '';
        $aplInfo['msa_info'][0]['ID'] = 11;
        $aplInfo['msa_info'][0]['status'] = '0';

        $result = array(
          'total_info' => array(
            'quota' => '5',
            'contract_cnt' => '3',
            'use_cnt' => '4',
            'unavailable_cnt' => '5',
          ),
          'contract_info' => array(
            '0' => array(
              'vlan_id' => '806',
              'tenant_name' => '',
              'IaaS_tenant_id' => '',
              'ID' => 11,
              'task_status' => '0',
              'use_status' => '0',
            )
          )
        );

        //case 2
        $stb = $this->getMock('msa_vlan',array( '_getQuotaMsa', '_getContractCntMsa', '_getUseCntMsa', '_getUnavailableCntMsa'));
        $stb->expects($this->any())->method('_getQuotaMsa')->will($this->returnValue(5));
        $stb->expects($this->any())->method('_getContractCntMsa')->will($this->returnValue(3));
        $stb->expects($this->any())->method('_getUseCntMsa')->will($this->returnValue(4));
        $stb->expects($this->any())->method('_getUnavailableCntMsa')->will($this->returnValue(5));
        $this->assertEquals( $method->invoke($stb, $aplInfo),$result);

    }

    /**
     * @covers msa_vlan::_execResult
     * @todo   Implement testExecResult().
     */
    public function testExecResult()
    {
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type'] = 'msa_vlan';
        $_SERVER['REQUEST_URI'] = "/Nal/resource/";
        $ret = new msa_vlan();
        $method = new ReflectionMethod($ret, '_execResult');
        $method->setAccessible(true);

        $url = 'http://127.0.0.1/Nal/';

        // case 1
        $err = array();
        $this->assertEquals($method->invoke($ret,$err,$url),'');

        // case 2
        $err['result'] = array( 'error-code' => 'NAL100000', 'message' => '' );
        try{
            $method->invoke($ret,$err,$url);
        }catch(Exception $e){
            $this->assertEquals('',$e->getMessage());
        }

        // case 3
        $err['result'] = array( 'error-code' => 'NAL140001', 'message' => 'test' );
        try{
            $method->invoke($ret,$err,$url);
        }catch(Exception $e){
            $this->assertEquals('test',$e->getMessage());
        }
    }

}
