<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-02 at 13:47:50.
 */

require_once dirname(__FILE__) . '/../Nal/api/app/wan_vlan.php';

class wan_vlanTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var wan_vlan
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        if( !defined('PHPUNIT_RUN')) {
            define( 'PHPUNIT_RUN', 1 );
        }
        $this->homeDir = realpath( dirname(__FILE__) ) ;
        if( !defined('HOME_DIR')) {
            define( 'HOME_DIR', $this->homeDir );
        }
        if( !defined('API_DIR')) {
            define( 'API_DIR' , HOME_DIR . '' );
        }
        if( !defined('APP_DIR')) {
            define( 'APP_DIR' , API_DIR . '/Stub' );
        }
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers wan_vlan::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // case 1
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_SERVER['REQUEST_URI'] = '/Nal/resource/';
        $_GET['function_type']    = 'wan_vlan';
        $_GET['scenario']         = 'resource';

        $ret = new wan_vlan();
        $method = new ReflectionMethod( $ret, 'get' );
        $method->setAccessible( true );

        $result = array(
          'total_info' => array(
            'contract_cnt' => '1'
          ),
          'contract_info' => array(
            'node_id' => '1234'
          )
        );

        $wimResult = array(
            'result' => array(
                'status' => 'success'
            ),
            'data' => array(
                'test' => '1'
            )
        );

        //case 1
        $stb = $this->getMock('wan_vlan',array('_execMultiApi', '_execApi', '_getContInfo', 'success'));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnValue(array()));
        $stb->expects($this->any())->method('_execApi')->will($this->returnValue($wimResult));
        $stb->expects($this->any())->method('_getContInfo')->will($this->returnValue($result));
        $stb->expects($this->any())->method('success')->will($this->returnArgument(0));
        $this->assertEquals( $method->invoke($stb), '');

        //case 2
        $stb = $this->getMock('wan_vlan',array('_execMultiApi', 'success'));
        $stb->expects($this->any())->method('_execMultiApi')->will($this->returnArgument(0));
        $stb->expects($this->any())->method('success')->will($this->returnValue($wimResult));
        $stb->_nalConf['api_type'] = 'wim'; // Wim
        $this->assertEquals( $method->invoke($stb),'');

    }

    /**
     * @covers wan_vlan::_getContInfo
     * @todo   Implement testgetContInfo().
     */
    public function testgetContInfo(){
        // case 1
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_SERVER['REQUEST_URI'] = '/Nal/resource/?function_type=license&type=1&device_type=1';
        $_GET['function_type']    = 'wan_vlan';
        $_GET['scenario']         = 'resource';

        $ret = new wan_vlan();
        $method = new ReflectionMethod( $ret, '_getContInfo' );
        $method->setAccessible( true );

        $aplInfo = array();
        $aplInfo['wan_info'][0]['vlan_id'] = '806';
        $aplInfo['wan_info'][0]['group_id'] = 'group1234';
        $aplInfo['wan_info'][0]['ID'] = 11;
        $aplInfo['wan_info'][0]['status'] = '1';
        $aplInfo['wan_info'][1]['vlan_id'] = '807';
        $aplInfo['wan_info'][1]['group_id'] = 'group1234';
        $aplInfo['wan_info'][1]['ID'] = 13;
        $aplInfo['wan_info'][1]['status'] = '1';
        $aplInfo['dc_group_info'][0]['group_id'] = 'group1234';
        $aplInfo['dc_group_info'][0]['tenant_name'] = 'tenant';
        $aplInfo['dc_group_info'][0]['IaaS_tenant_id'] = '1234';
        $aplInfo['dc_group_info'][1]['group_id'] = 'group0123';
        $aplInfo['dc_group_info'][1]['tenant_name'] = 'tenant2';
        $aplInfo['dc_group_info'][1]['IaaS_tenant_id'] = '0123';

        $result = array(
          'total_info' => array(
            'quota' => '5',
            'contract_cnt' => '3',
            'use_cnt' => '4',
            'unavailable_cnt' => '5',
          ),
          'contract_info' => array(
            '0' => array(
              'vlan_id' => '806',
              'tenant_name' => 'tenant',
              'IaaS_tenant_id' => '1234',
              'ID' => 11,
              'task_status' => '1',
              'use_status' => '1',
            ),
            '1' => array(
              'vlan_id' => '807',
              'tenant_name' => 'tenant',
              'IaaS_tenant_id' => '1234',
              'ID' => 13,
              'task_status' => '1',
              'use_status' => '1',
            )
          )
        );

        //case 1
        $stb = $this->getMock('wan_vlan',array( '_getQuotaWan', '_getContractCntWan', '_getUseCntWan', '_getUnavailableCntWan'));
        $stb->expects($this->any())->method('_getQuotaWan')->will($this->returnValue(5));
        $stb->expects($this->any())->method('_getContractCntWan')->will($this->returnValue(3));
        $stb->expects($this->any())->method('_getUseCntWan')->will($this->returnValue(4));
        $stb->expects($this->any())->method('_getUnavailableCntWan')->will($this->returnValue(5));
        $this->assertEquals( $method->invoke($stb, $aplInfo),$result);

        $ret = new wan_vlan();
        $method = new ReflectionMethod( $ret, '_getContInfo' );
        $method->setAccessible( true );

        $aplInfo = array();
        $aplInfo['wan_info'][0]['vlan_id'] = '806';
        $aplInfo['wan_info'][0]['group_id'] = '';
        $aplInfo['wan_info'][0]['ID'] = 11;
        $aplInfo['wan_info'][0]['status'] = '0';
        $aplInfo['dc_group_info'][0]['group_id'] = 'group1234';
        $aplInfo['dc_group_info'][0]['tenant_name'] = 'tenant';
        $aplInfo['dc_group_info'][0]['IaaS_tenant_id'] = '1234';
        $aplInfo['dc_group_info'][1]['group_id'] = 'group0123';
        $aplInfo['dc_group_info'][1]['tenant_name'] = 'tenant2';
        $aplInfo['dc_group_info'][1]['IaaS_tenant_id'] = '0123';

        $result = array(
          'total_info' => array(
            'quota' => '5',
            'contract_cnt' => '3',
            'use_cnt' => '4',
            'unavailable_cnt' => '5',
          ),
          'contract_info' => array(
            '0' => array(
              'vlan_id' => '806',
              'tenant_name' => '',
              'IaaS_tenant_id' => '',
              'ID' => 11,
              'task_status' => '0',
              'use_status' => '0',
            )
          )
        );

        //case 2
        $stb = $this->getMock('wan_vlan',array( '_getQuotaWan', '_getContractCntWan', '_getUseCntWan', '_getUnavailableCntWan'));
        $stb->expects($this->any())->method('_getQuotaWan')->will($this->returnValue(5));
        $stb->expects($this->any())->method('_getContractCntWan')->will($this->returnValue(3));
        $stb->expects($this->any())->method('_getUseCntWan')->will($this->returnValue(4));
        $stb->expects($this->any())->method('_getUnavailableCntWan')->will($this->returnValue(5));
        $this->assertEquals( $method->invoke($stb, $aplInfo),$result);

    }

    /**
     * @covers wan_vlan::_execResult
     * @todo   Implement testExecResult().
     */
    public function testExecResult()
    {
        $_SERVER['REQUEST_METHOD'] = 'GET';
        $_GET['function_type'] = 'wan_vlan';
        $_SERVER['REQUEST_URI'] = "/Nal/resource/";
        $ret = new wan_vlan();
        $method = new ReflectionMethod($ret, '_execResult');
        $method->setAccessible(true);

        $url = 'http://127.0.0.1/Nal/';

        // case 1
        $err = array();
        $this->assertEquals($method->invoke($ret,$err,$url),'');

        // case 2
        $err['result'] = array( 'error-code' => 'NAL100000', 'message' => '' );
        try{
            $method->invoke($ret,$err,$url);
        }catch(Exception $e){
            $this->assertEquals('',$e->getMessage());
        }

        // case 3
        $err['result'] = array( 'error-code' => 'NAL140001', 'message' => 'test' );
        try{
            $method->invoke($ret,$err,$url);
        }catch(Exception $e){
            $this->assertEquals('test',$e->getMessage());
        }
    }

}
