<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<metadata>
    <map>
        <entry>
            <key>DISPLAYNAME</key>
            <value>Task_Get_NS_LCM_Operation_Occurrence_State.py</value>
        </entry>
        <entry>
            <key>DATE_MODIFICATION</key>
            <value>1642587460297</value>
        </entry>
        <entry>
            <key>REPOSITORY</key>
            <value>Process</value>
        </entry>
        <entry>
            <key>DATE_CREATION</key>
            <value>1642587460295</value>
        </entry>
        <entry>
            <key>TAG</key>
        </entry>
        <entry>
            <key>FILE_TYPE</key>
            <value>text</value>
        </entry>
        <entry>
            <key>TYPE</key>
            <value>UPLOAD</value>
        </entry>
        <entry>
            <key>COMMENT</key>
        </entry>
    </map>
</metadata>
