resource : "MGMOSSMEMBERPWD"
method   : "POST"
inpara   :
 we_passwd : ""
 auth_method_kbn : "1"
 auth_type : "0"
 auth_id : "administrator1@aa.moss-test1.com"
 auth_pwd : "2147483647"
 req_madr : "test"
 req_pwd : "test"
