resource : "MOSSGAODNY"
method   : "POST"
inpara   :
 we_passwd : "aaa"
 auth_method_kbn : "1"
 auth_type : "0"
 auth_id : "wetest_01@aa.moss-test1.com"
 auth_pwd : "746574657465"
 dnyfil_type : "from_fil"
 dnyfil_mode : "S"
 #dnyfil_mode : "1"
 #dnyfil_mode : "9"
 dnyfil_data_count : "0"
 #dnyfil_data[n] : ""

