resource : "MOSSMEMBER"
method   : "GET"
inpara   :
 we_passwd : "aaa"
 auth_method_kbn : "1"
 auth_type : "0"
 auth_id : "wetest_01@aa.moss-test1.com"
 auth_pwd : "746574657465"
 hi_auth_id : ""
 hi_op_auth_type : ""
