resource : "MOSSMEMBER"
method   : "DELETE"
inpara   :
 we_passwd : "aaa"
 auth_method_kbn : "2"
 auth_type : "0"
 auth_id : "administrator1@aa.moss-test1.com"
 auth_pwd : "313131313131"
 hi_auth_id : "wetest_02@aa.moss-test1.com"
 hi_auth_id[2] : "wetest_03@aa.moss-test1.com"
 hi_auth_id[3] : "wetest_03@aa.moss-test1.com"
 hi_auth_id[4] : "wetest_03@aa.moss-test1.com"
 hi_auth_id[5] : "wetest_03@aa.moss-test1.com"
 hi_auth_id[6] : "wetest_03@aa.moss-test1.com"
 hi_auth_id[7] : "wetest_03@aa.moss-test1.com"
 hi_auth_id[8] : "wetest_03@aa.moss-test1.com"
 hi_auth_id[9] : "wetest_03@aa.moss-test1.com"
 hi_auth_id[10] : "wetest_03@aa.moss-test1.com"
 index_free4 : "25"
 index_free4[2] : "25"
 index_free4[3] : "25"
 index_free4[4] : "25"
 index_free4[5] : "25"
 index_free4[6] : "25"
 index_free4[7] : "25"
 index_free4[8] : "25"
 index_free4[9] : "25"
 index_free4[10] : "25"
